### ISSUE TITLE
[Bug] JMESPath query command has too much arguments

### ISSUE THREAD

**Issue by el-memer** [kyverno/website#1007]
### Page link

https://kyverno.io/docs/writing-policies/external-data-sources/#handling-collections

### Description

Kyverno commands provided to test JMESPath queries are wrong

```shell
╰─ kubectl get --raw /api/v1/namespaces | kyverno jp query "items[?metadata.name == 'default'].{name: metadata.name, creationTimestamp: metadata.creationTimestamp}"                         ─╯

Error: error evaluating JMESPath expression: Unknown key "query" in path
```

### Expected behavior

Remove `query` from `jp` command

```shell
╰─ kubectl get --raw /api/v1/namespaces | kyverno jp "items[?metadata.name == 'default'].{name: metadata.name, creationTimestamp: metadata.creationTimestamp}"                             ─╯

[
  {
    "creationTimestamp": "2023-03-21T13:36:58Z",
    "name": "default"
  }
]

```

**Comment by chipzoller** [comment]
Docs of a given version always represent code from that version. The `query` command was introduced in Kyverno CLI 1.10. Earlier versions did not have that command. Refer to earlier versions of the docs if you are on them.

**Comment by el-memer** [comment]
My bad, I just followed doc installation without noticing that in the version 1.10 of the doc, the [manual binary installation](https://kyverno.io/docs/kyverno-cli/#manual-binary-installation) makes you install version 1.7.2 of kyverno :see_no_evil: 
Sorry about the noise !

**Comment by chipzoller** [comment]
>the [manual binary installation](https://kyverno.io/docs/kyverno-cli/#manual-binary-installation) makes you install version 1.7.2 of kyverno

That's the CLI, not the webhook, and as stated in the docs is only an example of how to do it.
