### ISSUE TITLE
Update doc for patchesJSON6902

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#102]
Supported use cases are documented at https://github.com/kyverno/kyverno/pull/1645 - `Proposed changes`.

**Comment by chipzoller** [comment]
@realshuting please see PR https://github.com/kyverno/website/pull/148 and comment/review if you think this addition is sufficient to capture the changes reflected in the linked kyverno/kyverno issue and PR.

**Comment by realshuting** [comment]
> @realshuting please see PR #148 and comment/review if you think this addition is sufficient to capture the changes reflected in the linked kyverno/kyverno issue and PR.

Thanks @chipzoller - this should be sufficient!
