### ISSUE TITLE
[Bug] Search is broken

### ISSUE THREAD

**Issue by aslafy-z** [kyverno/website#1020]
### Page link

https://main.kyverno.io/docs/

### Description

Search popover does not open anymore. 

I believe the issue was added with https://github.com/kyverno/website/pull/904. 

See console errors:

![image](https://github.com/kyverno/website/assets/8191198/e86732a3-3b7a-4e4c-9448-f8de592d587c)

### Expected behavior

Search works.

**Comment by chipzoller** [comment]
cc @onweru, can you help out here, please 🙏

**Comment by onweru** [comment]
@chipzoller, I have reviewed this and it indeed seems to have been introduced in docsy __v0.7.1__; and we missed it in #904. This I think only affects Lunar Search, not Algolia. There were several commits alluding to this problem in [v.0.7.2](https://github.com/google/docsy/releases/tag/v0.7.2). I can try to track down the changes but it's not trivial, hence I need some time.

**Comment by chipzoller** [comment]
They released 0.8.0. Is it fixed there?

**Comment by onweru** [comment]
I checked, it's fixed but it's not plug and play as we need to fix breaking changes that it brings.

**Comment by chipzoller** [comment]
Are those breaking changes in separate areas or is this all related to search?
