### ISSUE TITLE
[Bug] Missing `s` for foreach-json-patch ClusterPolicy

### ISSUE THREAD

**Issue by RelativeSure** [kyverno/website#1021]
### Page link

https://kyverno.io/docs/writing-policies/mutate/

### Description

There's a missing `s` for the ClusterPolicy example with the name `foreach-json-patch`.
Needs to be `operations:` but instead it is `operation:`

### Expected behavior

Add missing `s`

**Comment by 1Shubham7** [comment]
Hey @RelativeSure, Can I solve this?

**Comment by RelativeSure** [comment]
> Hey @RelativeSure, Can I solve this?

Hi!
Yeah go for it 😊

**Comment by 1Shubham7** [comment]
Hey @RelativeSure, 
This has already been solved. 
![image](https://github.com/kyverno/website/assets/116020663/9b040639-2b5c-42b8-bee1-b04f438a6972)

Kindly check - https://github.com/kyverno/website/blob/main/content/en/docs/Writing%20policies/mutate.md

**Comment by RelativeSure** [comment]
> Hey @RelativeSure, 
> This has already been solved. 
> ![image](https://github.com/kyverno/website/assets/116020663/9b040639-2b5c-42b8-bee1-b04f438a6972)
> 
> Kindly check - https://github.com/kyverno/website/blob/main/content/en/docs/Writing%20policies/mutate.md
> 

Hi,
The issue is on the website, I had hoped I could fix it myself but I don't know it its because the site hasn't been updated or there's another bug with the site.

**Comment by 1Shubham7** [comment]
I think the website is just not updated. When I am running locally it says "opeartions". I think the issue is solved.
![image](https://github.com/kyverno/website/assets/116020663/b007460d-df26-4ad0-9293-38dece9508a0)

**Comment by RelativeSure** [comment]
> I think the website is just not updated. When I am running locally it says "opeartions". I think the issue is solved.
> ![image](https://github.com/kyverno/website/assets/116020663/b007460d-df26-4ad0-9293-38dece9508a0)
> 

Yeah, I agree. Do we know how to make the website get updated so it gets fixed?

**Comment by chipzoller** [comment]
It's fixed: https://kyverno.io/docs/writing-policies/mutate/#foreach
