### ISSUE TITLE
[Enhancement] Fine-Grained Exclusions in Kyverno's Validate.podSecurity Rule

### ISSUE THREAD

**Issue by itsgurmannatsohal** [kyverno/website#1023]
### Overview:
Kyverno aims to introduce implemented support for fine-grained exclusions in the `validate.podSecurity` rule in version 1.8.0. This enhancement enables users to apply Pod Security Standards to selected containers while allowing exclusions based on `restrictedFields` and their corresponding values.
[Implementation](https://github.com/kyverno/kyverno/pull/8585)

### Documentation Update:
We need to create comprehensive documentation to guide users on leveraging the newly implemented feature. The documentation should cover:

#### Feature Overview:
Provide a brief introduction to the fine-grained exclusion feature in the `validate.podSecurity` rule.
Explain the benefits of using this feature in enhancing security configurations.

#### Configuration Guide:
Detail the syntax and usage of the `validate.podSecurity` rule with a focus on specifying exclusions through `restrictedFields`.
Provide examples illustrating common use cases to help users understand the practical application of this feature.

#### Best Practices:
Offer recommendations and best practices for effectively utilizing fine-grained exclusions.
Highlight potential pitfalls and how to avoid them.

#### Troubleshooting:
Include a troubleshooting section addressing common issues users may encounter.
Provide guidance on debugging and resolving problems related to the fine-grained exclusion feature.

#### Release Notes:
Document the implementation details in the release notes for version 1.8.0 or the relevant release.

**Comment by chipzoller** [comment]
This has a hard dependency on PR #7412 which itself has a hard dependency on an upstream PR to Kubernetes https://github.com/kubernetes/kubernetes/pull/117059. Until both are merged, this cannot be worked on. When it is, the documentation would only affect the released version incorporating those changes, not an earlier version such as 1.8.0.

**Comment by itsgurmannatsohal** [comment]
[kyverno/kyverno#7412 ](https://github.com/kyverno/kyverno/pull/7412) has been continued in [kyverno/kyverno#8585 ](https://github.com/kyverno/kyverno/pull/8585) and is in the process of being approved.

**Comment by chipzoller** [comment]
Apparently the dependency on upstream Kubernetes is not true so this only relies upon the PR to kyverno/kyverno being merged.
