### ISSUE TITLE
[Enhancement] making `images` consistent with `image`

### ISSUE THREAD

**Issue by 1Shubham7** [kyverno/website#1064]
### Description

The issue was with the `images` variable not having the same fields as `image` variable. We added two fields `Reference` and `ReferenceWithTag` to make both of them consistent.

### Expected behavior

We need to document [this issue](https://github.com/kyverno/kyverno/pull/9147)

**Comment by chipzoller** [comment]
@1Shubham7, can you please send a PR for the documentation now that the code PR has been merged? This was included in 1.11.2 so can be written now.

**Comment by 1Shubham7** [comment]
sure @chipzoller
