### ISSUE TITLE
[Bug] making the front matter consistent across the project

### ISSUE THREAD

**Issue by 1Shubham7** [kyverno/website#1082]
### Description

Not a major update but the front matter is inconsistent across different files in the project. e.g. 

For the [community/_index page](https://github.com/kyverno/website/blob/main/content/en/Community/_index.md?plain=1) we have - 
```
---
title: Community
linkTitle: "Community"
type: docs
---
```

While for [docs/introduct/_index page](https://github.com/kyverno/website/blob/main/content/en/docs/Introduction/_index.md?plain=1) we have 
```
---
title: "Introduction"
linkTitle: "Introduction"
weight: 10
```

### Expected behavior

It's a minor update but we should follow the actual Docsy format for front matter i.e.
```
---
title: "My amazing new section"
weight: 1
type: docs
description: >
  A special section with a docs layout.  
---
```

**Comment by chipzoller** [comment]
Not all pages need the same type of frontmatter and what Docsy is suggesting isn't necessarily something that must apply universally. Some of this is standard YAML (folded line scalars versus nothing) as well.

**Comment by 1Shubham7** [comment]
yes it's not necessary, I thought let's have similar format across all files in the proj. You can consider closing the PR and the issue.
