### ISSUE TITLE
[Bug] Kyverno report enforced policies result scrape 

### ISSUE THREAD

**Issue by vponoikoait** [kyverno/website#1121]
### Page link

https://kyverno.io/docs/policy-reports/

### Description

Kyverno report enforced policies result 

### Expected behavior

According to https://github.com/kyverno/kyverno/issues/5347
That's possible to scrape reports from reporter via related tooling (policy reporter)
https://kyverno.io/docs/policy-reports/ 
But in documentation itself it's stated differently 
```
Policies configured with spec.validationFailureAction: Enforce immediately block violating resources and results will only be reported for pass evaluations
```
Would it be possible to adjust corresponding thread, or provide example on how reporting of enforced would be achieved? As well as update documentation accordingly, in case if it's achievable on current stage. Having blog on how to handle reports for enforced policies which aren't passing would be nice as well.

**Comment by vponoikoait** [comment]
@chipzoller please, suggest

**Comment by chipzoller** [comment]
They're two different things: policy reports and Events. The Policy Reporter project can scrape both. Resources denied (not created) as a result of a validate rule in `Enforce` mode will not create a policy report result. I'm not sure what you want fixed/clarified here in the docs.

**Comment by vponoikoait** [comment]
@chipzoller inside of the Policy Reporter repo itself 
https://github.com/kyverno/policy-reporter 
It's just more PolicyReport centric here in **README** which makes it unclear. Not much of blogs may cover theme, so I haven't so far actually found some solution or answer to my question. 
"""
Kyverno ships with two types of validation. You can either enforce a rule or audit it. If you don't want to block developers or if you want to try out a new rule, you can use the audit functionality. The audit configuration creates [PolicyReports](https://kyverno.io/docs/policy-reports/) which you can access with kubectl. Because I can't find a simple solution to get a general overview of this PolicyReports and PolicyReportResults, I created this tool to send information about PolicyReports to different targets like [Grafana Loki](https://grafana.com/oss/loki/), [Elasticsearch](https://www.elastic.co/de/elasticsearch/) or [Slack](https://slack.com/).
"""

I will try to dig into it tomorrow and maybe I will find suitable reference to work on top of. In case if you've any you would be able to share, I will be highly thankful for a such.

**Comment by chipzoller** [comment]
cc @fjogeleit for input

**Comment by chipzoller** [comment]
Policy Reporter docs are located here: https://kyverno.github.io/policy-reporter/

**Comment by fjogeleit** [comment]
https://kyverno.github.io/policy-reporter/guide/helm-chart-core#enable-enforce-violation-policyreports-requires-kyverno-170

Is the link to the feature you mentioned, whicj creates policy reports out of enforce validation events

**Comment by chipzoller** [comment]
Thanks, Frank.

Since this doesn't appear to be anything for the Kyverno docs, I'm closing.
