### ISSUE TITLE
[1.12] Update Argo CD notes with webhook labels 

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#1128]
### Description

https://github.com/kyverno/kyverno/pull/9015 adds a webhook labels key primarily intended for Argo CD users. Add this to the [Notes for ArgoCD Users](https://kyverno.io/docs/installation/platform-notes/#notes-for-argocd-users) section.

**Comment by thesuperzapper** [comment]
For the reasons outlined in https://github.com/kyverno/kyverno/issues/9551, there are still users who will be unable to guarantee the removal of the webhooks with the new label value.

Namely those who use ArgoCD's annotation tracking mode.
