### ISSUE TITLE
[Bug] Documentation text does not match example and default kyverno config map

### ISSUE THREAD

**Issue by myron-randall** [kyverno/website#1131]
### Page link

https://kyverno.io/docs/installation/customization/#resource-filters

### Description

In the resource filter documentation it says to use the following: "data.resourceFilters must be a sequence of one or more `[<Kind>,<Namespace>,<Name>]` entries with * as a wildcard. ", but in the example of the config map below it has an entry of "`resourceFilters: '[*/*,kyverno,*]`" which does not seem to match the documentation for the wildcard. The `*/*` is not explained. Also in the default kyverno config map it has some entries with a colon at the end of the name. `[RoleBinding,kyverno,kyverno:admission-controller]`. This is not explained in the documentation either. 

### Expected behavior

Clear documentation on the resource filter

**Comment by chipzoller** [comment]
> Also in the default kyverno config map it has some entries with a colon at the end of the name. `[RoleBinding,kyverno,kyverno:admission-controller]`. This is not explained in the documentation either.

The docs explain that the third position is the resource name. `kyverno:admission-controller` is the name of the RoleBinding resource.
