### ISSUE TITLE
[Bug] document the existence of `BACKGROUND_SCAN_INTERVAL`

### ISSUE THREAD

**Issue by thesuperzapper** [kyverno/website#1141]
### Page link

https://kyverno.io/docs/installation/customization/

### Description

Currently the "Configuring Kyverno" makes no reference to a very important config `BACKGROUND_SCAN_INTERVAL`, an environment variable for the background controller pods which determines how often to re-sync "generate" and "mutate" rules.

For reference, the code location which reads `BACKGROUND_SCAN_INTERVAL` is here (defaults to `1h`):

- https://github.com/kyverno/kyverno/blob/v1.11.4/cmd/background-controller/main.go#L121

We should explain what it is, how `BACKGROUND_SCAN_INTERVAL` is different to `--backgroundScanInterval` (for the reports controller), and how to set it in the helm chart using the `backgroundController.extraEnvVars` value, like this:

```yaml
backgroundController:
  extraEnvVars:
    - name: BACKGROUND_SCAN_INTERVAL
      value: 10m
```

Related to https://github.com/kyverno/kyverno/issues/9560

### Expected behavior

That users are told about `BACKGROUND_SCAN_INTERVAL`, especially because its so easy to confuse with `--backgroundScanInterval`

**Comment by coder12git** [comment]
I would like to take this, @realshuting can you please assign this to me?

**Comment by coder12git** [comment]
There are few things (not brief ) are mentioned [here](https://kyverno.io/docs/writing-policies/mutate/#mutate-existing-resources) about `BACKGROUND_SCAN_INTERVAL`

**Comment by chipzoller** [comment]
I'll take this one.

**Comment by chipzoller** [comment]
I don't think it's worth starting a new section elsewhere for one env var so I think the present location is ok.

**Comment by thesuperzapper** [comment]
> I don't think it's worth starting a new section elsewhere for one env var so I think the present location is ok.

@chipzoller Can we at least put a warning beside `backgroundScanInterval` which says that it's NOT the same as `BACKGROUND_SCAN_INTERVAL`?

Specifically on the "Configuring Kyverno" page:
- https://kyverno.io/docs/installation/customization/#container-flags

I'm sure I'm not the only one who's been confused by it, and tried to set it with the `--backgroundScanInterval` flag on the background controller, only to find (after much testing) that it doesn't work, because it can only be set with that environment variable.
