### ISSUE TITLE
[Enhancement] Automate doc updates for CLI 

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#1146]
### Description

https://github.com/kyverno/kyverno/pull/9651#issuecomment-1929504074

cc @eddycharly 

### Slack discussion

n/a

**Comment by chipzoller** [comment]
I don't think this issue fully covers any and all doc updates needed in the CLI. This is about command-level docs and not usage or use case docs. We need both.

**Comment by chipzoller** [comment]
I think @eddycharly addressed this in #1179. Reopen if that's not the case.
