### ISSUE TITLE
[Enhancement] Server-side diff now available in Argo CD 2.10.0

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#1147]
### Description

https://github.com/argoproj/argo-cd/releases/tag/v2.10.0

Would be nice to add to the Platform Notes section for users.

**Comment by JimBugwadia** [comment]
I can help do this, had done a blog post on this topic:

https://www.cncf.io/blog/2024/01/18/gitops-and-mutating-policies-the-tale-of-two-loops/
