### ISSUE TITLE
[Enhancement] add new flag `loggingtsFormat`

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#1167]
### Description

https://github.com/kyverno/kyverno/pull/9276

**Comment by coder12git** [comment]
@realshuting this needs to be documented in this section - https://kyverno.io/docs/installation/customization/#container-flags
right?
I would like to take this!

**Comment by realshuting** [comment]
> @realshuting this needs to be documented in this section - https://kyverno.io/docs/installation/customization/#container-flags right? I would like to take this!

Yes, assigned!

**Comment by realshuting** [comment]
Hi @coder12git - I have switched the default logging format to RFC3339 via https://github.com/kyverno/kyverno/pull/9775 for the easier readability.

**Comment by coder12git** [comment]
> Hi @coder12git - I have switched the default logging format to RFC3339 via [kyverno/kyverno#9775](https://github.com/kyverno/kyverno/pull/9775) for easier readability.

@realshuting 
![image](https://github.com/kyverno/website/assets/108334168/c8c6810c-a622-486c-9cb2-9d0f2104bd01)

I think this flag is already present, just need to chnage the default value?

**Comment by mviswanathsai** [comment]
It is also this change present in the current code [here](https://github.com/kyverno/website/blob/42f991b331d606a0aec3ba551dc931ffa7194a93/content/en/docs/Installation/customization.md?plain=1#L332). But I am unable to see it reflected in the website.  
![image](https://github.com/kyverno/website/assets/110663831/2eb94f20-e175-455a-8ae9-005d07783257)

**Comment by coder12git** [comment]
> It is also this change present in the current code [here](https://github.com/kyverno/website/blob/42f991b331d606a0aec3ba551dc931ffa7194a93/content/en/docs/Installation/customization.md?plain=1#L332). But I am unable to see it reflected in the website. ![image](https://private-user-images.githubusercontent.com/110663831/307280098-2eb94f20-e175-455a-8ae9-005d07783257.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODE3ODksIm5iZiI6MTcwODY4MTQ4OSwicGF0aCI6Ii8xMTA2NjM4MzEvMzA3MjgwMDk4LTJlYjk0ZjIwLWUxNzUtNDU1YS04YWU5LTAwNWQwNzc4MzI1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QwOTQ0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmRiNGVkZTBjYjViNDEzZmEwMWNmNDYwNjc1OTA2NzE3ZTNmNjI4YWQ0OTdiYTQzMDczNzkwYTIzNThiZWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HGLIBeEH-VYXfut9OekpAE5qYHUPk3VQKApZS5Uy2hE)

Yes, right i saw this change locally
