### ISSUE TITLE
[Bug] imageRegistryCredentials.secret is not actually a key, correct key is imageRegistryCredentials.secrets

### ISSUE THREAD

**Issue by Drauren** [kyverno/website#1170]
### Page link

https://kyverno.io/docs/writing-policies/verify-images/

### Description

In the documentation on how to configure verify-image, the imageRegistryCredentials.secret key is documented as used for passing a list of k8s secrets with image pull credentials. This is wrong. The key is imageRegistryCredentials.secrets.

### Expected behavior

Documentation updated to reflect imageRegistryCredentials.secrets as the correct key.

**Comment by coder12git** [comment]
Thanks, for informing @Drauren. I have created the PR with that change. 
//@realshuting
