### ISSUE TITLE
Require Labels

### ISSUE THREAD

**Issue by igorkchyts** [kyverno/website#119]
The policy description does not match the purpose of 'require-labels' rule but instead, it matches the 'Disallow-latest-tag' policy.

**Comment by chipzoller** [comment]
@igorkchyts Can you point us to where you're seeing this? It doesn't appear to be the [sample policy](https://kyverno.io/policies/best-practices/require_labels/require_labels/) and it doesn't appear to be in-text example in the quick start guide [here](https://kyverno.io/docs/introduction/#quick-start).

**Comment by igorkchyts** [comment]
@chipzoller I can see it is correct. I saw the issue [here](https://kyverno.io/policies/best-practices/require_labels/require_labels/) before and opened this issue directly by clicking "Create Project Issue" on the right of the page. 

Closing this issue.
