### ISSUE TITLE
[Bug] Checklist before becoming a Maintainer has a link to the outdated certificate

### ISSUE THREAD

**Issue by KhaledEmaraDev** [kyverno/website#1250]
### Page link

https://github.com/kyverno/website/blob/main/content/en/community/_index.md

### Description

Checklist before becoming a maintainer has a link to the outdated certificate

### Expected behavior

Link to the new CNCF certificate

**Comment by chipzoller** [comment]
Proposal is to remove this?

**Comment by chipzoller** [comment]
Current docs do not have a link to any certification program, only a text line item. Nothing to do at this time. Closing.
