### ISSUE TITLE
[Bug] Container flag `omitEvents` is missing

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#1284]
### Description

https://github.com/kyverno/kyverno/pull/9572/files fixes the container flag but it's not documented.

`--omitEvents` is available for the admission controller, the background controller and the report controller:

>Set this flag to a comma sperated list of PolicyViolation, PolicyApplied, PolicyError, PolicySkipped to disable events, e.g. --omitEvents=PolicyApplied,PolicyViolation

### Expected behavior

Add the flag.

### Slack discussion

n/a

**Comment by realshuting** [comment]
This need to be backport to 1.12.

**Comment by chipzoller** [comment]
It's already there but I recently fixed the name. The fix is in main.

https://kyverno.io/docs/installation/customization/#container-flags

**Comment by realshuting** [comment]
> It's already there but I recently fixed the name. The fix is in main.
> 
> https://kyverno.io/docs/installation/customization/#container-flags

Are we going to cherry-pick it to 1.12?

**Comment by chipzoller** [comment]
#1285
