### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by rameshneela** [kyverno/website#1353]
### Description

We plan to import the Kyverno GitHub repository into our local GHE repository and use it from there. Could you please outline the steps we need to follow for this process, as well as any documentation or updates that need to be completed?
For instance, we need to update the Artifactory repository URL to point to the organization-level repository, etc.

### Expected behavior

Documentation steps and details

**Comment by realshuting** [comment]
Hi @rameshneela - thanks for raising the issue. I don't know if we can help much here. Kyverno is an Open Source Project and feel free to fork the repo and customize it if needed.

I'm closing the issue as it's out of Kyverno's scope. We can continue the discussion here though.
