### ISSUE TITLE
[Enhancement] Add CORS headers to blog RSS feed

### ISSUE THREAD

**Issue by not7cd** [kyverno/website#1367]
### Description

I wanted to add News feed in my Grafana dashboard to not miss any minor update. Unfortunately, it's not working. Grafana points out to lack of CORS headers since in recent versions the frontend handles News panel.

See: https://cors-test.codehappy.dev/?url=https%3A%2F%2Fkyverno.io%2Fblog%2Findex.xml&origin=https%3A%2F%2Fcors-test.codehappy.dev%2F&method=get

**Comment by realshuting** [comment]
Hi @not7cd - thanks for raising the issue, what would be the proper fix to this?

**Comment by not7cd** [comment]
I found that you are using Netlify, I added an entry to enable CORS for all.
