### ISSUE TITLE
[Bug] Red Hat support statement is not correct

### ISSUE THREAD

**Issue by snecklifter** [kyverno/website#1391]
### Page link

https://kyverno.io/support/redhat/

### Description

The page indicates Red Hat supports Kyverno PolicySets however this was a Tech Preview feature in 4.11 and never made it to General Availability.

### Expected behavior

Removal of page indicating Red Hat support.

For clarity I work for Red Hat but I am not filing this on behalf of my employer. This is following internal discussions and some confusion over the supported nature of Kyverno in OpenShift.

**Comment by realshuting** [comment]
Thanks for raising the issue @snecklifter, we can remove this section from our doc, feel free to open a PR!
