### ISSUE TITLE
Creation of deployment in "require-labels" example succeeds in kyverno namespace

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#14]
Possibly a documentation issue or a misunderstanding. When using the "require-labels" example ClusterPolicy, creation of the nginx deployment fails as expected in the default (possibly other) namespaces but succeeds in the `kyverno` namespace if this was the namespace used to install kyverno itself. Why?

**Comment by JimBugwadia** [comment]
@chipzoller - Kyverno can be configured to exclude certain namespaces. By default, the `kyverno` namespace is excluded as are other system namespaces. More details in this section of the docs: https://kyverno.io/docs/installation/#resource-filters.
