### ISSUE TITLE
[Bug] Quickstart "require-labels" file doesn't deploy

### ISSUE THREAD

**Issue by quietstormio** [kyverno/website#1413]
### Page link

https://kyverno.io/docs/introduction/quick-start/

### Description

Getting the following error after copying and pasting from my clipboard and writing a file then kubectl create command:

"Error from server (BadRequest): error when creating "labelPolicy.yaml": ClusterPolicy in version "v1" cannot be handled as a ClusterPolicy: strict decoding error: unknown field "spec.rules[0].validate.failureAction"

This is after installing Kyverno with the Helm chart on the same page.

### Expected behavior

No errors.

**Comment by JimBugwadia** [comment]
I tried with a latest Helm chart and it worked.

Can you please check your versions?

```sh
kubectl -n kyverno get deploy -o yaml | grep "image:"
          image: ghcr.io/kyverno/kyverno:v1.13.0
          image: ghcr.io/kyverno/kyvernopre:v1.13.0
          image: ghcr.io/kyverno/background-controller:v1.13.0
          image: ghcr.io/kyverno/cleanup-controller:v1.13.0
          image: ghcr.io/kyverno/reports-controller:v1.13.0
```

**Comment by cerebro1** [comment]
Please /assign
I will verify this.

**Comment by cerebro1** [comment]
Verified and the code block mentioned in the doc seems to be working fine. I have tried installation via Helm and via release manifest. Applying the "require-labels" policy works in both scenarios.
Here is the detailed output for Helm setup and deployment of policy:

Install via Helm:
```
$ helm install kyverno kyverno/kyverno -n kyverno --create-namespace
NAME: kyverno
LAST DEPLOYED: Mon Dec 23 17:56:26 2024
NAMESPACE: kyverno
STATUS: deployed
REVISION: 1
NOTES:
Chart version: 3.3.4
Kyverno version: v1.13.2

Thank you for installing kyverno! Your release is named kyverno.

The following components have been installed in your cluster:
- CRDs
- Admission controller
- Reports controller
- Cleanup controller
- Background controller
```

Apply the validate policy:
```
$ kubectl create -f- << EOF
> apiVersion: kyverno.io/v1
> kind: ClusterPolicy
> metadata:
>   name: require-labels
> spec:
>   rules:
>   - name: check-team
>     match:
>       any:
>       - resources:
>           kinds:
>           - Pod
>     validate:
>       failureAction: Enforce
>       message: "label 'team' is required"
>       pattern:
>         metadata:
>           labels:
>             team: "?*"
> EOF
clusterpolicy.kyverno.io/require-labels created
```

Please verify the version of Kyverno you have on your cluster using the following command:
```
$ kubectl -n kyverno get deploy -o yaml | grep "image:"
          image: ghcr.io/kyverno/kyverno:v1.13.2
          image: ghcr.io/kyverno/kyvernopre:v1.13.2
          image: ghcr.io/kyverno/background-controller:v1.13.2
          image: ghcr.io/kyverno/cleanup-controller:v1.13.2
          image: ghcr.io/kyverno/reports-controller:v1.13.2
         ```
 The above output shows that version 1.13.2 is installed on my cluster. Upgrade to the latest and let us know if you still face an issue. Feel free to reopen this issue with more details or you can start a thread on our Slack channel where our team can help you debug or troubleshoot.
 
 @team Please close the issue for now.
