### ISSUE TITLE
Update note for ArgoCD users

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#1437]
> Probably not relevant anymore but I stumbled across the same issue and was able to fix it.
> 
> The issue started to occur when we used “Server Side Apply” instead of “Replace” when applying Kyverno resources. Adding the following annotation to my argo app fixed the issue for us:
> 
> ```
> kind: Application
> metadata:
>   annotations:
>     argocd.argoproj.io/compare-options: ServerSideDiff=true
> ```

@FrittenToni - thanks for sharing, it would be good to add a note for [ArgoCD users](https://kyverno.io/docs/installation/platform-notes/#notes-for-argocd-users):
> ArgoCD uses Helm only for templating but applies the results with kubectl. Unfortunately kubectl adds metadata that exceeds the limit allowed by Kubernetes. Using Replace overcomes this limitation. Another option is to use server-side apply, supported in ArgoCD v2.5+.

_Originally posted by @realshuting in https://github.com/kyverno/kyverno/issues/9451#issuecomment-2478409636_

**Comment by JimBugwadia** [comment]
We have this mentioned here:

https://kyverno.io/docs/writing-policies/mutate/#argocd-v210

We can move them to:

https://kyverno.io/docs/installation/platform-notes/#notes-for-argocd-users

And reference in the mutation section.

**Comment by realshuting** [comment]
Another [note](https://github.com/kyverno/kyverno/issues/10283#issuecomment-2479039962) to add - 

> I removed the Replace=true sync option to keep only the ServerSideApply=true

**Comment by Mohdcode** [comment]
i never tried writing the documentation maybe i should give it a GO!

**Comment by Mohdcode** [comment]
Please could you assign it to me

**Comment by realshuting** [comment]
> Please could you assign it to me

Assigned!

**Comment by cerebro1** [comment]
Looks like the above PR has fixed the issue. If there are no more requirements, please close the issue @realshuting. Thanks!
