### ISSUE TITLE
[Enhancement] Cosmetic issue in Kyverno Architecture Diagram

### ISSUE THREAD

**Issue by lakshmanandevops** [kyverno/website#1444]
### Description

Kyverno Architecture Diagram has a cosmetic issue in the page https://kyverno.io/docs/introduction/how-kyverno-works/

PolicyExceptions is underlined in red (Due to spell check not ignored) . This can be updated so we do not see red lines

![Architecture](https://github.com/user-attachments/assets/56771ad6-49d5-4578-bbc8-00040c12535c)

**Comment by cerebro1** [comment]
Please close the issue as this is now fixed.
