### ISSUE TITLE
Add github stars to the home page

### ISSUE THREAD

**Issue by patelrit** [kyverno/website#160]
It would be nice to show the current github stars on the how page and add a link so that users can star the project if they like it.

**Comment by chipzoller** [comment]
> on the how page

On the home page?

We do have this as shown below, and if a user clicks on "stars" it'll direct them to the kyverno/kyverno GitHub repo allowing them to star it.

![image](https://user-images.githubusercontent.com/29008123/117488218-23e36080-af3a-11eb-91f1-44c7918bf94c.png)

**Comment by patelrit** [comment]
I was thinking something like this
![image](https://user-images.githubusercontent.com/3522560/117489980-153d7f00-af23-11eb-9f71-1fa8a8cf8f50.png)
