### ISSUE TITLE
Resource Definitions

### ISSUE THREAD

**Issue by viveksahu26** [kyverno/website#173]
I was going through the documentation part of Resource Definitions. Under "[kubectl explain](https://kyverno.io/docs/crds/#kubectl-explain)" section in "policy.spec"  file. In line number 1, I don't understand the meaning of  "λ". It doesn't suit here.
And I line 8, 
`Spec defines policy behaviors and contains one or rules.`.
According to me, it would be 
`Spec defines policy behaviors and contains one or more rules.`

**Comment by JimBugwadia** [comment]
@viveksahu26 - `λ` is the prompt in the Cmdr shell - I agree it should be removed.

Do you want to submit a PR for this and fixing the sentence, `Spec defines policy behaviors and contains one or rules`?

**Comment by chipzoller** [comment]
Note that the schema definition needs to be fixed in kyverno/kyverno as well (this PR simply fixes the output but the source of it remains).
