### ISSUE TITLE
Selecting Resources

### ISSUE THREAD

**Issue by viveksahu26** [kyverno/website#181]
Under `[Match statements]`, in the second paragraph, [line](https://kyverno.io/docs/writing-policies/match-exclude/#match-statements) no. 1 
`In this snippet, the match statement matches on any **and** all resources that have the kind Service.`. 
According to me, it is more below statement will be more meaningful than the above statement,
`In this snippet, the match statement matches on any **or** all resources that have the kind Service.` .
Because at one point in time it can select either any resources or all resources, if it selects any then it can't select all or if selects all then no meaning of any.

**Comment by chipzoller** [comment]
Maybe rephrasing like this is clearer still:

_In this snippet, the match statement matches on all resources that have the kind Service._

**Comment by viveksahu26** [comment]
> Maybe rephrasing like this is clearer still:
> 
> _In this snippet, the match statement matches on all resources that have the kind Service._

>@chipzoller, yes it is more clear statement.

**Comment by chipzoller** [comment]
Would you be willing to open a PR for this and your [other suggested correction](https://github.com/kyverno/website/issues/186)?

**Comment by chipzoller** [comment]
@viveksahu26 are you taking care of this?

**Comment by viveksahu26** [comment]
@chipzoller , i am sorry. I forgot. 
Yes, i will take care of this.

**Comment by viveksahu26** [comment]
@chipzoller , I have already made changes to it and it's has been already updated there. You can close this issue now.

**Comment by viveksahu26** [comment]
[PR](https://github.com/kyverno/website/pull/191/files) was merged for the above issue.
