### ISSUE TITLE
Kind is not mandatory while working with resource element, it's optional.

### ISSUE THREAD

**Issue by viveksahu26** [kyverno/website#185]
In the paragraph containing [`match.resources.kinds`](https://kyverno.io/docs/writing-policies/match-exclude/) in the second line, it is mentioned that 
`The kind attribute is mandatory when working with the resources element`. But, it is not so. Though in most of the cases in which the `resource` element is present for matching resources but not everywhere. Here is a reference to one of the [cases](https://kyverno.io/docs/writing-policies/match-exclude/#match-a-label-and-exclude-users-and-roles).  The correct statement would be,
 `The kind attribute is optional when working with the resources element`.

**Comment by JimBugwadia** [comment]
@viveksahu26 a `kind` is required for the `match`.

**Comment by viveksahu26** [comment]
In the paragraph containing match.resources.kinds in the second line, it is mentioned that
`The kind attribute is mandatory when working with the resources element`. But, it is not so. Here is a reference to one of the cases where a kind attribute is not mandatory when working with the resources element. 
The correct statement would be,
`The kind attribute is optional when working with the resources element`.

**Comment by viveksahu26** [comment]
@JimBugwadia, can you check, I have updated.

**Comment by chipzoller** [comment]
At one point in time, `kind` was optional. However, that has since been changed and `kind` is now mandatory as you have pointed out in [this other issue](https://github.com/kyverno/policies/issues/68).

**Comment by viveksahu26** [comment]
Yes,  Kind attribute is compulsory in resource element. So, for the same, we need to update this [policy ](https://github.com/kyverno/policies/blob/main/other/block_updates_deletes.yaml)and the [example](https://kyverno.io/docs/writing-policies/match-exclude/#match-a-label-and-exclude-users-and-roles).

**Comment by viveksahu26** [comment]
Issue is resolved. [PR](https://github.com/kyverno/website/pull/192) merged.
