### ISSUE TITLE
Kyverno CLI

### ISSUE THREAD

**Issue by viveksahu26** [kyverno/website#186]
Just below the `The test declaration consists of three parts` [section](https://kyverno.io/docs/kyverno-cli/#test). I didn't get this statement `The test command executes a test declaration by applying the policies to the results and comparing the results with the expected results`. More specifically, this part `applying the policies to the results`. As per my understanding, policies are applied to resources. The correct statement would be `applying the policies to the resources`.

**Comment by chipzoller** [comment]
Your correction looks to be more appropriate. Can you open a PR with the fix?

**Comment by viveksahu26** [comment]
Required changes/bugs are updated now.
