### ISSUE TITLE
Selecting Resources, "Exclude kube-system namespace" needs `resources` key name

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#19]
The [Exclude kube-system namespace](https://kyverno.io/docs/writing-policies/match-exclude/#exclude-kube-system-namespace) example needs to have `resources` inserted after the `exclude` statement or else the rule will not be applied. See also [this thread](https://kubernetes.slack.com/archives/CLGR9BJU9/p1605030837128600) in Kyverno Slack for details.

**Comment by realshuting** [comment]
Thanks @chipzoller , sent the [PR](https://github.com/kyverno/website/pull/18) to fix it.

**Comment by chipzoller** [comment]
Apologies. Didn't see the PR when I created issue.
