### ISSUE TITLE
No need for a note that multiple replicas are not supported.

### ISSUE THREAD

**Issue by sotoiwa** [kyverno/website#201]
At the top of the installation page, there is a note that multiple replicas are not supported, but the roadmap item has already been closed and is supported in v1.4.0 and later. Therefore, this statement should be removed or updated.

https://kyverno.io/docs/installation/
https://github.com/kyverno/kyverno/issues/1214

**Comment by chipzoller** [comment]
Thanks for the report, @sotoiwa . We are a bit behind on documentation but will make this update.
