### ISSUE TITLE
Copy button for code blocks

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#21]
You all have spent a lot of time writing some neat policies in the docs. It would be great if users could, with a simple button, copy the whole code block to the clipboard. Not sure what is being used for the site itself, else I would suggest.

**Comment by chipzoller** [comment]
So it's the [docsy](https://themes.gohugo.io/docsy/) theme built with Hugo, which doesn't appear to have a copy button.

**Comment by chipzoller** [comment]
This is something I'm going to look at trying to include from our [Clarity theme](https://themes.gohugo.io/hugo-clarity/) once we release v2.

**Comment by JimBugwadia** [comment]
Looks like Kubernetes docs, using the same theme, now have a copy button. Here's an example:

https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/#limit-access-to-the-nginx-service

We can check how its implemented.

**Comment by chipzoller** [comment]
I already implemented it. Both branches have it now. 🙂

**Comment by JimBugwadia** [comment]
Awesome! Closing...
