### ISSUE TITLE
Update metric-related docs with the respect to recent metric updates in Kyverno

### ISSUE THREAD

**Issue by yashvardhan-kukreja** [kyverno/website#239]
The metric design was recently upgraded in Kyverno to deal with cardinality explosion.
Refer: https://github.com/kyverno/kyverno/pull/2157

Update the metric-related docs to comply with the new metrics.

**Comment by chipzoller** [comment]
Milestone 1.4.2, yes?

**Comment by yashvardhan-kukreja** [comment]
> Milestone 1.4.2, yes?

Yep
