### ISSUE TITLE
Specifying names in the match/exclude block

### ISSUE THREAD

**Issue by sotoiwa** [kyverno/website#242]
[The document](https://kyverno.io/docs/writing-policies/match-exclude/#advanced-match-statement) says that `names` which is array can be specified in the match/exclude block, but in fact it cannot. On the other hand, `name` whicht is not array can be specified.

I'm not sure if this is a documentation bug or an implementation bug.

```shell
error: error validating "restricted.yaml": error validating data: ValidationError(ClusterPolicy.spec.rules[0].match.resources): unknown field "names" in io.kyverno.v1.ClusterPolicy.spec.rules.match.resources; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by chipzoller** [comment]
This is a mistake on my part as "names" is coming in 1.4.2 and we merged it too soon. It'll be fixed. Apologies for that.
