### ISSUE TITLE
Update doc for ConfigMap lookup

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#25]
The docs need to be updated regarding:

- The variable substitution does not apply to `match` / `exclude` when looking up data from a ConfigMap
- Special characters `-`, `/` need to be skipped in a JMESPATH style expression, see https://github.com/kyverno/kyverno/pull/1118#issuecomment-696321894

**Comment by realshuting** [comment]
@JimBugwadia 
More to update - let's document the variable substitution behavior, as users may want to know how does it work if later the configMap changes. 

One of the questions @chipzoller had:
>If a ConfigMap is created with an array of values, then a policy is created referencing it, what happens if the ConfigMap is later updated? Does the policy read the data in the ConfigMap at the time the policy is evaluated, or is the data inserted into the policy and not rechecked after the policy is created?

**Comment by chipzoller** [comment]
I was actually making an edit to the docs right now to address the question. @JimBugwadia has given me push access, so I can commit directly to the website repo now.

**Comment by realshuting** [comment]
This is great, thanks @chipzoller !

**Comment by chipzoller** [comment]
Closing with 7483b6b87cec097e9c723b3425d9c68c89dad282.
