### ISSUE TITLE
Clarify generate behaviors for existing resources

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/website#28]
Explain how to introduce a new generate policy and apply to existing resources (e.g. namespaces).

**Comment by chipzoller** [comment]
Covered.

**Comment by chipzoller** [comment]
Check commit on dev https://github.com/kyverno/website/commit/10fb2972725c016a7d1367a23f3d6a7aaa7bd24f

**Comment by chipzoller** [comment]
Closing based on earlier commit. Reopen if insufficient.
