### ISSUE TITLE
[Docs] Adding pod anti-affinity to Kyverno

### ISSUE THREAD

**Issue by NoSkillGirl** [kyverno/website#301]
Related issue - https://github.com/kyverno/kyverno/issues/1966
Fix - https://github.com/kyverno/kyverno/pull/1985

Add the documentation for adding pod anti-affinity to Kyverno.

**Comment by NoSkillGirl** [comment]
I wanted to add that we support enabling and disabling the pod anti-affinity rules, using the following flag:
```
antiAffinity:
   # This can be disabled in a 1 node cluster.
   enable: true
```

**Comment by chipzoller** [comment]
Previous question still stands though. Where/how does this involve documentation?

**Comment by NoSkillGirl** [comment]
@realshuting - can you please help me here. Where should we mention the information about pod anti-affinity.

**Comment by realshuting** [comment]
Need to update this page https://github.com/kyverno/kyverno/tree/main/charts/kyverno#configuration.
