### ISSUE TITLE
[UI] Add a call to participate banner for "Adopters Program"

### ISSUE THREAD

**Issue by Anita-ihuman** [kyverno/website#302]
**Is your feature request related to a problem? Please describe current state:**
Website requires a call to participate banner for the Kyverno adopters program.

**Describe the solution you'd like:**
Create a component that calls users of Kyverno to participate in the proposed Adopters program.

**Contributor Resources**
- [Contributing Guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md)

**Comment by chipzoller** [comment]
How would you like to handle this?

**Comment by Anita-ihuman** [comment]
This will be added under the Community Doc, as a subheading.
