### ISSUE TITLE
[1.5.0] explain variable processing error handing in preconditions and rule specs

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/website#321]
In 1.5 we have improved the policy rule results to return `skip` and `error` based on rule processing:

- If a rule's match/exclude blocks are satisfied, but preconditions are not satisfied, the result is `skip`.
- If a rule's match/exclude blocks are satisfied, but a pattern is not satisfied, the result is `skip`.
- If variable is not resolved in a pre-condition, it is evaluated to an empty string `""` to allow existence checks.
- If a variable is not resolved in a spec, an error is returned for the rule status.

**Comment by chipzoller** [comment]
This logic only applies to the CLI, correct?

**Comment by realshuting** [comment]
It applies to both CLI and the controller.

**Comment by chipzoller** [comment]
Having a hard time figuring out where to squeeze this in. We don't document this processing today and it seems like it's more of an under-the-covers type thing. Is this something we should document? If so, would a new section under [Policies and Rules](https://kyverno.io/docs/kyverno-policies/) be the best place?

**Comment by realshuting** [comment]
Maybe we can add a new section `result` to [policy reports](https://kyverno.io/docs/policy-reports/) since this change will be reflected in the report results? Previously all the violations are marked as `fail` in the reports, this change identifies failures into `fail`, `skip`, and `error`, separately. This would impact how to build test results for CLI as well.

**Comment by chipzoller** [comment]
@JimBugwadia I am trying to close this issue but am not understanding your statement above:

> If a rule's match/exclude blocks are satisfied, but a pattern is not satisfied, the result is `skip`.

In testing this with a couple different policies and resources, if the match/exclude block is satisfied, there are no preconditions, and the pattern is not satisfied, the result is `fail`. How would the result of `skip` be produced here aside from when preconditions do not exist?

**Comment by chipzoller** [comment]
Also, how would `error` and `warn` be produced?

**Comment by chipzoller** [comment]
Bump. Last issue to close out in 1.5.0.

**Comment by chipzoller** [comment]
See linked PR for current copy.
