### ISSUE TITLE
[Docs] Policies filled with 404 towards https://github.com/kyverno/policies

### ISSUE THREAD

**Issue by vosdev** [kyverno/website#322]
**Is your feature request related to a problem? Please describe current state:**
2 weeks ago almost all policies were placed in their own subdirectory by this commit https://github.com/kyverno/policies/commit/b74f24030db59eaed64435dd10abbcda90eacff2

**Describe the solution you'd like:**
URLs to be updated :-)

example:
https://kyverno.io/policies/other/restrict_automount_sa_token/ links to:

https://github.com/kyverno/policies/raw/main//other/restrict_automount_sa_token.yaml
which should be:
https://github.com/kyverno/policies/raw/main/other/restrict_automount_sa_token/restrict_automount_sa_token.yaml

**Describe alternatives you've considered:**
N/A

**Additional context**
I'll get started on a PR!

**Contributor Resources**
- [Contributing Guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md)

**Comment by chipzoller** [comment]
See linked PR, but these updates happen via a separate rendering program which updates links.
