### ISSUE TITLE
Search is returning stale pages

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#33]
Haven't looked into how the docsy theme handles search results, but it's returning page links which aren't valid. As an example, do a search for "preconditions" and click the top link. Seems like it's not updating its cache of pages when the site gets updated.

**Comment by evalsocket** [comment]
@chipzoller we are using Google Custom Search Engine and it returns the google result. If you search `site:kyverno.io precondition` on google and click on the first result then it will cause the same issue. In google webmaster, there is an option for change the scraping interval. 

@JimBugwadia can you increase the time that google scrape the kyverno website using the sitemap.

**Comment by evalsocket** [comment]
If you see the [sitemap](https://kyverno.io/sitemap.xml) it is updated but I think google didn't scrape the updated docs.

**Comment by JimBugwadia** [comment]
This PR changed the search to use a local search. Try it at: https://deploy-preview-56--kyverno.netlify.app/.

**Comment by chipzoller** [comment]
Seems to be fine. Although search box doesn't work on the [CRDs page](https://deploy-preview-56--kyverno.netlify.app/docs/crds/) for some reason.

**Comment by JimBugwadia** [comment]
Ah, yes. We need to delete the CRDs page.  It is showing an outdated HTML that was manually generated from the schema types.

We can add text in the Writing policies section on how to use `kubectl explain` etc. to view the schema.

**Comment by chipzoller** [comment]
I put that in the [Tips & Tricks section](https://kyverno.io/docs/writing-policies/tips/#general), but maybe there's an additional place it should go as well. That said, it is, I think anyway, still very useful to have the schemata documented in textual format. But maybe there's a better way to generate that.

**Comment by JimBugwadia** [comment]
@chipzoller - here is a corresponding PR for the policies (titles, descriptions, etc.): https://github.com/kyverno/policies/pull/7.

Regarding the CRDs - perhaps we can generate and link to an HTML preview separate from the website, so its clear search, etc. will not work.

**Comment by chipzoller** [comment]
I've seen that done in other projects so it's worth a try here.

**Comment by JimBugwadia** [comment]
Closing this. I logged a separate issue for the CRD section.
