### ISSUE TITLE
[BUG] The accepted values for ConditionOperator are not documented

### ISSUE THREAD

**Issue by esantoro** [kyverno/website#340]
**Software version numbers**

* Kubernetes version: any
* Kubernetes platform (if applicable; ex., EKS, GKE, OpenShift): any
* Kyverno version: 1.4.3

**Describe the bug**

The possible values for `(Cluster)?Policy.spec.rules.[*].validate.deny.conditions.[*].operator` are not documented.

It is not clear what set of operators are supported, if the set of operators are supported to be a known set from some other technology and it is not clear what their syntax/semantics would be.

**To Reproduce**
1. Start writing a policy
2. Decide to use `deny/conditions`
3. Consult https://htmlpreview.github.io/?https://github.com/kyverno/kyverno/blob/main/docs/crd/v1/index.html#kyverno.io/v1.ConditionOperator for reference
4. Get confused

**Expected behavior**

A  link to a full, clear and concise description of all the supported operators should be present in the reference for the ConditionOperator.

**Screenshots**
![image](https://user-images.githubusercontent.com/34766/137772437-092e40d3-6304-4ebf-a090-8dafab85ea56.png)

**Additional context**

Examples would be appreciated too.

For the moment, the only useful thing one can do is to hunt down usages in the wild, such as in https://kyverno.io/policies/other/allowed_pod_priorities/ .

**Comment by chipzoller** [comment]
@esantoro I am looking into this. In your reference to the [Allowed Pod Priorities sample policy](https://kyverno.io/policies/other/allowed_pod_priorities/allowed_pod_priorities/), where does it reflect this undocumented ability?

**Comment by esantoro** [comment]
@chipzoller referring to the policy, take lines 40-42 as an example.

In the triple key/operator/value the key "operator" is the undocumented ability.

From that example I can desume that exist a "NotIn" operator (and thus probably an "In" operator too). 

However the question stands: where can I find a list of all the supported operators (ideally along with their syntax)?

**Comment by chipzoller** [comment]
The operators are all documented [here](https://kyverno.io/docs/writing-policies/preconditions/#operators) and are the same for `preconditions` and `deny.conditions` blocks. It's not clear from the documentation, so we probably need to explicitly state that these operators apply to both places.

**Comment by esantoro** [comment]
@chipzoller that's great, thank you!

Would it be possible to link the operators section you linked (https://kyverno.io/docs/writing-policies/preconditions/#operators) in the ClusterPolicy/Policy object reference?
