### ISSUE TITLE
[1.5.2] Add documentation for Escaping Variables and References

### ISSUE THREAD

**Issue by ojhaarjun1** [kyverno/website#348]
#### Related Issues
- kyverno/kyverno#2413
- kyverno/kyverno#2513

#### PRs
- kyverno/kyverno#2433
- kyverno/kyverno#2563

**Comment by chipzoller** [comment]
Need to know the corresponding milestone for this.

**Comment by realshuting** [comment]
Looks like two issues are in different milestones. @ojhaarjun1 - can you confirm?

**Comment by chipzoller** [comment]
Setting for 1.6.0

**Comment by chipzoller** [comment]
1.5.2 now
