### ISSUE TITLE
Resources page, putting dates (Month, Year) by resources

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#35]
Would anyone have a problem with putting a date next to these resources in parenthesis? Although they're ranked in descending order, it'd be much nicer to know when they were written at a glance.

**Comment by JimBugwadia** [comment]
No, that would be useful.

**Comment by chipzoller** [comment]
Closed via https://github.com/kyverno/website/commit/f7c259dc3e2392ae03d3f56d64cd62a23ffa916b
