### ISSUE TITLE
[BUG] Certificate Expiry time is not correct as per the document

### ISSUE THREAD

**Issue by abhishekghiya** [kyverno/website#360]
Hello,

As per Kyverno doc the certificate validity is mentioned as 10 years but when verified the certificate as below the validity seems to be only 1 year.

![image](https://user-images.githubusercontent.com/76930832/138804865-1725e038-da16-4fc1-ad5e-78ed0f686200.png)

![image](https://user-images.githubusercontent.com/76930832/138804956-86877386-a712-4cb7-b208-dbaf9e9f8909.png)

Thanks

**Comment by chipzoller** [comment]
For a highly-available installation, yes, more than one (and recommended 3) must be available. There is some work pending on certificate handling in manual mode being tracked [here](https://github.com/kyverno/kyverno/issues/1886). I'll fix this line in the documentation.

**Comment by chipzoller** [comment]
@eddycharly the leaf and the CA will be regenerated automatically, correct?

**Comment by eddycharly** [comment]
Yes, they will be regenerated.
The current implementation is not graceful though.
It should be soon, I’m currently implementing graceful certs rotation.

**Comment by chipzoller** [comment]
Any docs modifications needed to accompany your improvements?

**Comment by eddycharly** [comment]
Some elements in the docs will become obsolete.
The graceful notation can be done only when kyverno manages the certificates. If a user brings his own certs, he takes the responsibility of the rotation gracefulness. We could describe the procedure.

Can you create an issue to track docs improvements in this area ?

**Comment by chipzoller** [comment]
#532

**Comment by pratik705** [comment]
Thanks @chipzoller @eddycharly for the prompt reply. I was planing to use cert-manager to manage the certs. But, I will proceed with the default certs as it will get auto-renewed on expiry.
