### ISSUE TITLE
Update Installation using YAML URL

### ISSUE THREAD

**Issue by ShubhamPalriwala** [kyverno/website#369]
**Is your feature request related to a problem? Please describe current state:**
 
We do not have a `definitions/release/install.yaml` on our kyverno/main anymore. Hence most of such URLs on our website give a 404. However, our `release 1.5` branch has it.

**Describe the solution you'd like:**

 We can rather change them to the latest release to fix this or add it to our main branch to avoid incosistency!

**Contributor Resources**
- [Contributing Guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md)

**Comment by chipzoller** [comment]
This was just committed: https://github.com/kyverno/website/pull/367

**Comment by ShubhamPalriwala** [comment]
Oh sort! GG will close this
