### ISSUE TITLE
Update doc for mutation overlay 

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#37]
With https://github.com/kyverno/kyverno/issues/1025, the overlay and patches in mutation will be deprecated and eventually removed from mutation policy. We need to update doc accordingly.

**Comment by chipzoller** [comment]
What is the first release scheduled for their removal?

**Comment by realshuting** [comment]
Will be removed in 1.5+: https://github.com/kyverno/kyverno/blob/7ee346b0decfeb16e4172cc2697ac329ee5583bf/pkg/api/kyverno/v1/policy_types.go#L202-L207

**Comment by chipzoller** [comment]
Closing via https://github.com/kyverno/website/commit/33ee26cded2cb52d83f3d6e52ea750f763ab442d
