### ISSUE TITLE
Installation link is broken

### ISSUE THREAD

**Issue by 100daysofdevops** [kyverno/website#370]
Installation link for the Document is broken
```
kubectl create -f https://raw.githubusercontent.com/kyverno/kyverno/main/definitions/release/install.yaml

error: unable to read URL "https://raw.githubusercontent.com/kyverno/kyverno/main/definitions/release/install.yaml", server reported 404 Not Found, status code=404
```

Reference: https://kyverno.io/docs/installation/#install-kyverno-using-yamls

**Comment by chipzoller** [comment]
Sorry for the inconvenience here. https://github.com/kyverno/website/pull/367 was already merged that fixes this, we just need to update the 1.5.0 release page. Closing this one as it's pending.
