### ISSUE TITLE
[1.5.0] Compatibility Matrix kyverno v1.5.x

### ISSUE THREAD

**Issue by superadri** [kyverno/website#377]
No documentation about Compatibility Matrix when kyverno version is v1.5.x.

**Comment by chipzoller** [comment]
Thanks for the heads-up, @superadri. I've transferred this to the website repo so we can get it added.

**Comment by superadri** [comment]
Could you provide me the Compatibility Matrix when Kyverno is 1.5.x?

**Comment by chipzoller** [comment]
Kyverno 1.5.x is still the same as 1.4.x. Will get this added as well.

**Comment by chipzoller** [comment]
Was added a while back.
