### ISSUE TITLE
[Docs] CRD spec for Rule.preconditions inconsistent with documentation

### ISSUE THREAD

**Issue by esantoro** [kyverno/website#382]
Hello,
I've noticed an inconsistency between the documentation in the kyverno website and the v1.Rule CRD spec (https://htmlpreview.github.io/?https://github.com/kyverno/kyverno/blob/main/docs/crd/v1/index.html#kyverno.io/v1.Rule).

Specifically, according to the v1.Rule CRD spec `Rule.preconditions` is an array of `Condition` objects:

![image](https://user-images.githubusercontent.com/34766/140963181-6c0a22a0-1de9-4955-92c5-8fdd267017d4.png)

However the "Any and all Statements" in the Preconditions documentation in the website (https://kyverno.io/docs/writing-policies/preconditions/#any-and-all-statements) describe the possibiliy of the preconditions not being an array of `Condition` objects but be an object instead, with two possible nested fields, `any` and `all`, both themselves being arrays of `Condition` objects. This other configuration as a fairly different semantic, as described in the documentation.

I would like to ask to update the  CRD spec to reflect this possibility.

**Comment by chipzoller** [comment]
Thanks for highlighting this. We're looking into it.

**Comment by chipzoller** [comment]
@JimBugwadia Can we get this updated to reflect current schema?

**Comment by chipzoller** [comment]
@esantoro the file has been updated (see linked PR and thanks @realshuting and @prateekpandey14)
