### ISSUE TITLE
[Docs] foreach only working on a list containing objects is not mentioned 

### ISSUE THREAD

**Issue by daniel-southwardellis** [kyverno/website#394]
**Is your feature request related to a problem? Please describe current state:**
While working on a kyverno policy using foreach I ran into issues with strange error messages. It turns out these occur because foreach only works on a list of objects but the docs don't mention this.

**Describe the solution you'd like:**
A short note next to the foreach paragraph in the docs reading something along the lines of:
Note: foreach can only loop over a list of objects, other types like strings and numbers are not supported and may result in strange errors.

**Comment by chipzoller** [comment]
Thanks for mentioning this. Will get this added.

**Comment by chipzoller** [comment]
I actually see this is covered in both the validate and mutate pages.

From the [validate page](https://kyverno.io/docs/writing-policies/validate/#foreach):

> Each `foreach` entry must contain a list attribute that defines the sub-elements it processes.

And from the [mutate page](https://kyverno.io/docs/writing-policies/mutate/#foreach):

> A `foreach` must contain a list attribute that defines the list of elements it processes

**Comment by daniel-southwardellis** [comment]
Ah so it does! My bad then, when I read it I thought element was used to mean item in list.
