### ISSUE TITLE
[Docs] - Add Support Partner Details

### ISSUE THREAD

**Issue by blakyaks** [kyverno/website#396]
**Is your feature request related to a problem? Please describe current state:**
No.

**Describe the solution you'd like:**
We would like our details added to the support page of the website.

**Describe alternatives you've considered:**
N/A

---
**Additional context**
Jim and Kim aware of the request and have advised on the process.

---
**Contributor Resources**
- [Contributing Guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md)

**Comment by chipzoller** [comment]
Closed by https://github.com/kyverno/website/pull/413
