### ISSUE TITLE
[Docs] Add doc to cover how to handle nodes shut down 

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#440]
**Is your feature request related to a problem? Please describe current state:**

Per the discussion in the contributors meeting on January 6th, 2022, it would be helpful to add the shutdown guidance for dealing with failed-closed configurations and clusters which are auto-scaled down to 0 nodes.

Related issue https://github.com/kyverno/kyverno/issues/2179.

**Comment by chipzoller** [comment]
Hi @realshuting do you think [this section](https://main.kyverno.io/docs/troubleshooting/#api-server-is-blocked) is enough to address this concern?
