### ISSUE TITLE
download kyverno SBOM's with versions/tags and verify signatures

### ISSUE THREAD

**Issue by Namanl2001** [kyverno/website#441]
related pr: https://github.com/kyverno/kyverno/pull/2979

## proposed changes

below are the proper instructions to download the SBOM:

```bash
$ export COSIGN_REPOSITORY=ghcr.io/kyverno/sbom
$ cosign download sbom ghcr.io/kyverno/kyverno:${TAG}  #this would return the sbom for tagged version eg: $ cosign download sbom ghcr.io/kyverno/kyverno:v1.6.1
```

to verify the signatures:
```bash
COSIGN_EXPERIMENTAL=1 COSIGN_REPOSITORY=ghcr.io/kyverno/signatures cosign verify ghcr.io/kyverno/kyverno:v1.6.1
```

**Comment by chipzoller** [comment]
@Namanl2001 I get the following when trying this right now:

```sh
$ export COSIGN_REPOSITORY=ghcr.io/kyverno/sbom
$ cosign download sbom ghcr.io/kyverno/kyverno:latest
Error: GET https://ghcr.io/v2/kyverno/sbom/manifests/sha256-fead173aaf13b0e5308fb52f88ce310d6309cba4d5d5eb4017f2874eb099061a.sbom: MANIFEST_UNKNOWN: manifest unknown
main.go:46: error during command execution: GET https://ghcr.io/v2/kyverno/sbom/manifests/sha256-fead173aaf13b0e5308fb52f88ce310d6309cba4d5d5eb4017f2874eb099061a.sbom: MANIFEST_UNKNOWN: manifest unknown
```

**Comment by Namanl2001** [comment]
@chipzoller - these commands would work, once the changes done in the related pr, lands in any kyverno release.

**Comment by chipzoller** [comment]
What do we need to add to the documentation based on this issue?

**Comment by Namanl2001** [comment]
for `1.6.0` - nothing, since the linked changes were then reverted in the `release-1.6` branch due to some failures. 

We are planning to add those changes back in the next release; then, we can add the instructions in the docs as mentioned in this pr's desc.

**Comment by chipzoller** [comment]
So are we closing this issue then?

**Comment by Namanl2001** [comment]
> So are we closing this issue then?

Ahh!! Then how are we gonna track that these changes needs to be done, in future

**Comment by Namanl2001** [comment]
> What specifically needs to be documented.

instructions to download SBOM, given in the PR description

> What release is this tracking for?

next kyverno release 1.6.x/1.7.0

**Comment by Namanl2001** [comment]
hi @chipzoller - we can add this PR's description in the website doc for `v1.6.1`

**Comment by Namanl2001** [comment]
> @Namanl2001 what is needed here now? I see this does work still:
> 
> ```
> cosign download sbom ghcr.io/kyverno/sbom:latest
> ```

hey @chipzoller - please observe the `component.version` field of the output you receive from above command. (`"version": "v1.6.1-rc1"`) which is wrong right? also in the same command if you will change the `latest` to any specific tag the you won't get any output. but with the instruction mentioned in the desc. you can pull the version specific SBOM's. (eg. v1.6.1, v1.6.2 or v1.7.0-rc3)

the second point mentioned about signature verification (in the issue desc) is not present in the docs, if I remember correctly. :)

**Comment by chipzoller** [comment]
What is the current instruction on how to retrieve this? Can you please provide as I have a docs PR open. Need to get this addressed.

**Comment by Namanl2001** [comment]
> What is the current instruction on how to retrieve this? Can you please provide as I have a docs PR open. Need to get this addressed.

I believe the instructions mentioned in the `proposed changes` section of this Issue description summarises the instructions pretty well, and they are also working fine as verified by me.

**Comment by chipzoller** [comment]
It does not appear to work for me:

```sh
$ COSIGN_REPOSITORY=ghcr.io/kyverno/sbom cosign download sbom ghcr.io/kyverno/kyverno:v1.7.0
WARNING: Downloading SBOMs this way does not ensure its authenticity. If you want to ensure a tamper-proof SBOM, download it using 'cosign download attestation <image uri>' or verify its signature.
Error: image not found in registry
main.go:52: error during command execution: image not found in registry
```

**Comment by chipzoller** [comment]
Problem is captured in https://github.com/kyverno/kyverno/issues/4083

**Comment by chipzoller** [comment]
The reason why the signature verification works is that we're creating signatures for BOTH the tagged and untagged images.

```sh
$ COSIGN_REPOSITORY=ghcr.io/kyverno/signatures COSIGN_EXPERIMENTAL=1 cosign verify ghcr.io/kyverno/kyverno:v1.7.0

Verification for ghcr.io/kyverno/kyverno:v1.7.0 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - Any certificates were verified against the Fulcio roots.

[{"critical":{"identity"<snip>
```

```sh
$ COSIGN_REPOSITORY=ghcr.io/kyverno/signatures COSIGN_EXPERIMENTAL=1 cosign verify ghcr.io/kyverno/kyverno@sha256:31238b385193fe96f9c02070fe87a9ebfafa26efc9fd78110293988a2c89a110

Verification for ghcr.io/kyverno/kyverno@sha256:31238b385193fe96f9c02070fe87a9ebfafa26efc9fd78110293988a2c89a110 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - Any certificates were verified against the Fulcio roots.

[{"critical":{"identity"<snip>
```

**Comment by chipzoller** [comment]
Re-opened https://github.com/kyverno/kyverno/issues/4083 as not resolved.
