### ISSUE TITLE
[Docs] Document `imageRegistry` context variable

### ISSUE THREAD

**Issue by samj1912** [kyverno/website#442]
**Is your feature request related to a problem? Please describe current state:**
 
See https://github.com/kyverno/kyverno/pull/2946 and https://github.com/kyverno/kyverno/issues/2939 for more details on the new feature. We should document this under external data access and also add some example sample policies that use this. 

Some ideas - 
 - resolve image tags for custom resource (without verifying them). 
 - Reject images that run as root
 - Validate volumes based on `VOLUME` instructions defined in the image. See https://github.com/kyverno/kyverno/pull/2946#issuecomment-1013748310
 - 
**Describe the solution you'd like:**

**Describe alternatives you've considered:**

---
**Additional context**

---
**Contributor Resources**
- [Contributing Guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md)

**Comment by chipzoller** [comment]
Sample policies for this image data functionality are being recorded here until the feature releases: https://github.com/kyverno/policies/issues/226
