### ISSUE TITLE
[Docs] Quick start documentation fix

### ISSUE THREAD

**Issue by rahulii** [kyverno/website#457]
while following this docs https://kyverno.io/docs/introduction/ , I tried to create a ClusterPolicy and then tried to create a deployment without the required label , but there was no error.
I later realized that I was creating a po/deployment in `kyverno` namespace
Could we document this , saying to create a deployment not in `kyverno` ns?

**Comment by chipzoller** [comment]
Did you not copy and apply the convenient code block from the same page (which doesn't specify the `kyverno` Namespace)?

![image](https://user-images.githubusercontent.com/29008123/151700833-21e991a2-68d6-4f9b-9c02-a1cf44a44a2c.png)

**Comment by JimBugwadia** [comment]
@rahulii - I will add a note regarding the namespaces.
