### ISSUE TITLE
[Docs] The download URL in kyverno doc for v1.4.3 is mapped to the wrong path

### ISSUE THREAD

**Issue by dolisss** [kyverno/website#464]
The download URL in Kyverno doc for v1.4.3 does not work as it is mapped to the wrong path:

![image](https://user-images.githubusercontent.com/71091713/152473348-fd4632cd-b701-4443-96d5-b7bc4f619132.png)

Solution: it should map to the right path 

Thanks,
Dolis

**Comment by chipzoller** [comment]
Thanks for the notification. Current path is found as stated [here](https://kyverno.io/docs/installation/#install-kyverno-using-yamls).
