### ISSUE TITLE
Rebase dev

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#48]
@JimBugwadia can you rebase dev from main so the branches are even, please?

**Comment by JimBugwadia** [comment]
@chipzoller - here are the steps to execute:

1. Get the latest `main` and `dev`

```sh
git checkout main
git pull --all

git checkout dev
git pull --all
```

2. Merge main to dev

```sh
git merge main
```

3. Push dev to origin

```
git push dev
```

**Comment by chipzoller** [comment]
I'll try that if you can accept the latest PR I just filed.

**Comment by chipzoller** [comment]
Done. Thank you.
