### ISSUE TITLE
[Bug] Document test of policies with apiCall

### ISSUE THREAD

**Issue by hoerup** [kyverno/website#485]
### Page link

https://kyverno.io/docs/kyverno-cli/#test

### Description

I couldn't deduct from the documentation, how the test command should behave when testing a policy that fetches data via apiCall

### Expected behavior

The doc should be expanded with info on how to test policies that utilizes apiCall

**Comment by chipzoller** [comment]
Great point to bring up. 100% right we can make this clearer and I'll include this in the next updates.
