### ISSUE TITLE
Clarify any and all

### ISSUE THREAD

**Issue by hoerup** [kyverno/website#491]
### Description

Current documentation lacks a description of whether the any and all operators execute their checks in defined order?
Also it doesn't mention whether the checks are performed in a short-circuit manner so one can utilize the order to simplify any following checks.

https://en.wikipedia.org/wiki/Short-circuit_evaluation

**Comment by chipzoller** [comment]
These are being tracked in:

https://github.com/kyverno/kyverno/issues/3474
https://github.com/kyverno/kyverno/issues/3475
