### ISSUE TITLE
[Bug] Webhookconfigurations deploy with failurePolicy: Ignore

### ISSUE THREAD

**Issue by karlschriek** [kyverno/website#495]
### Page link

https://kyverno.io/docs/installation/#webhooks

### Description

Using this installation (1.6.1), https://raw.githubusercontent.com/kyverno/kyverno/release-1.6/config/release/install.yaml, the `kyverno-policy-*`  webhook confiruation for are all set to `failurePolicy: Ignore`, which seems to run contrary to what is described in the documentation here: https://kyverno.io/docs/installation/#webhooks. Both `kyverno-resource-*` and `kyverno-verify-*` are set to `failurePolicy: Fail` as expected.

### Expected behavior

I would expect the documentation to explain why it is like this. I initially thought that this was actually a bug and opened an issue on it here: https://github.com/kyverno/kyverno/issues/3455

**Comment by chipzoller** [comment]
The manifest currently points to 1.6.2 which no longer has webhooks included as they are created and managed dynamically, so I think this is now a non-issue. If you still see an enhancement that we need to make regarding the documentation in this area, please comment.
