### ISSUE TITLE
[Enhancement] Add new container flags

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#496]
### Description

These [two container flags](https://github.com/kyverno/kyverno/pull/2797) need to be added to https://kyverno.io/docs/installation/#container-flags:

- clientRateLimitQPS: Configure the maximum QPS to the master from Kyverno. Uses the client default if zero.
- clientRateLimitBurst: Configure the maximum burst for throttle. Uses the client default if zero.

**Comment by oliverbaehler** [comment]
Hi, I just want to add my two cents on this. As Enduser setting those flags improved our performance tremendously. See the metrics:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/26610571/166816917-0582d583-19b4-4bf9-a5a6-ffd1a8666a4e.png)

Before they averaged somewhere around 10s (bcs we have some policies which query the API a lot etc.). I would recommend to point this out in the documentation, to spare other users the long search.

**Comment by chipzoller** [comment]
What values did you use?

**Comment by oliverbaehler** [comment]
```
"--clientRateLimitQPS": 50
"--clientRateLimitBurst": 100
````

**Comment by abhilashbs1981** [comment]
extraArgs:
  - "--clientRateLimitQPS=50"
  - "--clientRateLimitBurst=100"

Adding above in latest version of Kyverno causes pod in stuck status where it is adding below as argument which seems not correct 

        - name: kyverno
          image: "ghcr.io/kyverno/kyverno:v1.11.0"
          imagePullPolicy: IfNotPresent
          args:
            - --caSecretName=release-name-kyverno-svc.default.svc.kyverno-tls-ca
            - --tlsSecretName=release-name-kyverno-svc.default.svc.kyverno-tls-pair
            - --backgroundServiceAccountName=system:serviceaccount:default:kyverno-background-controller
            - --servicePort=443
            - --disableMetrics=false
            - --otelConfig=prometheus
            - --metricsPort=8000
            - --admissionReports=true
            - --autoUpdateWebhooks=true
            - --enableConfigMapCaching=true
            - --enableDeferredLoading=true
            - --dumpPayload=false
            - --forceFailurePolicyIgnore=false
            - --generateValidatingAdmissionPolicy=false
            - --loggingFormat=text
            - --v=2
            - --enablePolicyException=true
            - --protectManagedResources=false
            - --allowInsecureRegistry=false
            - --registryCredentialHelpers=default,google,amazon,azure,github
            **- --0=--clientRateLimitQPS=50
            - --1=--clientRateLimitBurst=100**
