### ISSUE TITLE
[Enhancement] Update Documentation for CLI test Cmd

### ISSUE THREAD

**Issue by vyankyGH** [kyverno/website#501]
### Description

1. Add Documentation For Mutate Policy.
2. Add Documentation for NamespaceSelector in values. yaml
3. Update kyverno-test.yaml for validate policy. Need to add Namespace field in result section which validate against the 
   specific namespace.
  https://github.com/kyverno/kyverno/blob/d97258654f4bcb1f3e85e7531df22de675a82a6e/test/cli/test/any-all-wildcard/kyverno-test.yaml#L11
4. Update the result table section to following format:
```
│───│───────────────────────────────│──────────│──────────────────────│────────│
│ # │ POLICY                        │ RULE     │ RESOURCE             │ RESULT │
│───│───────────────────────────────│──────────│──────────────────────│────────│
│ 1 │ disallow-protected-namespaces │ disallow │ namespace1/Pod/test1 │ Pass   │
│ 2 │ disallow-protected-namespaces │ disallow │ namespace2/Pod/test2 │ Pass   │
│ 3 │ disallow-protected-namespaces │ disallow │ namespace3/Pod/test3 │ Pass   │
│───│───────────────────────────────│──────────│──────────────────────│────────│
```

**Comment by vyankyGH** [comment]
@chipzoller I have added details. Let me know if we require any other details.

**Comment by chipzoller** [comment]
Link to https://github.com/kyverno/website/issues/506

**Comment by chipzoller** [comment]
The values file can also support nested objects rather than dot-separated ones.
