### ISSUE TITLE
[Bug] Generate policies should specify apiVersion in its rule definition

### ISSUE THREAD

**Issue by shubham4443** [kyverno/website#502]
### Description

Generate policies will be covered by the test command soon. See PR kyverno/kyverno#3456. The CLI requires that user mentions apiVersion in generate policy's rule definition otherwise the test command would print out wrong result. Additionally, it is best practice to specify apiVersion along with kind. We should add this extra field in the website wherever we find an example of generate policy.

### Expected behavior

apiVersion specified in rule definition of generate policies.

**Comment by chipzoller** [comment]
Also update existing generate policies to match.
