### ISSUE TITLE
[Bug]  Broken link's found in website

### ISSUE THREAD

**Issue by vyankyGH** [kyverno/website#526]
### Description

Page : https://kyverno.io/docs/policy-reports/
Search in page:  policy rule execution metric
broken ink: https://kyverno.io/docs/monitoring-kyverno-with-prometheus-metrics/policy-rule-results-info/

Page: https://kyverno.io/docs/monitoring/bonus-grafana-dashboard/
Images are not loading
https://raw.githubusercontent.com/kyverno/website/main/content/en/docs/Monitoring%20Kyverno%20With%20Prometheus%20Metrics/assets/dashboard-example-1.png
https://raw.githubusercontent.com/kyverno/website/main/content/en/docs/Monitoring%20Kyverno%20With%20Prometheus%20Metrics/assets/dashboard-example-2.png

Page: https://kyverno.io/docs/security/
search in page: (https://github.com/kyverno/kyverno/blob/main/cosign.pub)
broken link: https://github.com/kyverno/kyverno/blob/main/cosign.pub

Page: https://kyverno.io/docs/crds/
Search in page: kyverno/kyverno/pkg/api
broken link: https://github.com/kyverno/kyverno/tree/main/pkg/api

Page: https://kyverno.io/resources/
Search for : How Kyverno helps with policy management
Broken link: https://mccricardo.com/kyverno-roles/

Page: https://kyverno.io/community/
Search in page: incubation level
Broken link: https://github.com/cncf/toc/blob/main/process/graduation_criteria.adoc

### Expected behavior

Link should work or remove.

**Comment by chipzoller** [comment]
Fixed! Except the one on the Cosign.pub key. That was captured separately in #458 and is assigned to @JimBugwadia to fix.

How did you find these broken links? I assume you used a scanning tool of some sort. Can you let me know so I can incorporate that into future edits?
