### ISSUE TITLE
[Enhancement] Document best practices to manage kyverno policies through helm charts

### ISSUE THREAD

**Issue by MarcelMue** [kyverno/website#534]
### Description

We should provide some guidance to helm users on known pitfalls and best practices about kyverno policies in helm charts. 

This should include:
- Known issues with variable escaping
- Brief guidance on CI setups which allow policies to be tested with the kyverno CLI

**Comment by treydock** [comment]
Might be some useful examples here:

https://github.com/OSC/osc-helm-charts

It's at least one use case of kyverno-policies chart where I take the kyverno chart and make my own custom policies chart depend on Kyverno's chart so I can customize the Kyverno chart but also install my own policies all with single Helm install.

For CI I don't do much other than validate the policies apply without error. I also have similar testing to what Kyverno does using kyverno CLI.

Biggest pitfall I can think of is order. Just have to ensure Kyverno is installed first and the CRD is ready before adding policies.

**Comment by chipzoller** [comment]
@MarcelMue I could use your help with the first bullet point you made. For the second, see my PR #598 where I have requested your review.

**Comment by chipzoller** [comment]
One syntax: 

```
{{ `{{` }} request.object.spec.template.metadata.labels {{ `}}` }}
```

**Comment by chipzoller** [comment]
@MarcelMue would value your input here. Feel free to just leave as a comment in this issue.

**Comment by MarcelMue** [comment]
I am writing down my thoughts here first before organizing a bit better. Again sorry for the delay :(

The core understanding needed to successfully wrap kyverno policies in helm charts, is that both of them use `golang` templating for variable substitution. 

This immediately has some implications:
1. Both use exactly the same syntax to template in a variable (e.g. `{{ some_var }}`).
2. Golang templating does not have a way to indicate which substitution belongs to which executor (in this case `helm` or `kyverno`).

The main way to mitigate this issue is to use the fact that `helm` templating will always be executed before any `kyverno` templating takes place. This becomes clear if we think about the deployment pipeline: A helm chart is applied by helm to a cluster, which first substitutes any variables and then applies policies to the Kubernetes. Kyverno only reacts on policies which are already present in Kubernetes and substitutes variables when an event triggers the policy.

When put in practice this means that the template step executed by helm should ignore any templates meant for kyverno AND produce a valid golang template to be executed by Kyverno. The best way to achieve this is to put any template meant for kyverno as a [String Literal](https://go.dev/ref/spec#String_literals) in the helm chart.

### Example
In the chart:
```
{{`{{ request.userInfo.username }}`}} {{ some.helm.value }}`
```
After helm templating:
```
{{ request.userInfo.username }} helmvalue
```
After Kyverno templating:
```
myuser helmvalue
```

A big problem with this general approach is readability. Wrapping any kyverno templating into string literals causes a lot of noise in a file - this is exacerbated if the same file contains a lot of templating meant for helm and kyverno.

This problem can be partially rectified by having a "pre-build" step before building your helm chart. To outline the idea:
1. Decide a new delimiter for e.g. Helm templating - so all helm templates look like `[[ some.helm.value]]`
2. Replace the delimiter meant for Kyverno with a string literal.
3. Replace the delimiter for helm templating with the actual delimiter ( so `[[` becomes `{{` and `]]` becomes `}}`).

### Example
In your git repo:
```
{{ request.userInfo.username }} [[ some.helm.value ]]
```
After step 2 of pre-build:
```
{{ `{{` }} request.userInfo.username {{ `}}` }} [[ some.helm.value ]]
```
After step 3 of pre-build:
```
{{ `{{` }} request.userInfo.username {{ `}}` }} {{ some.helm.value }}
```

This approach has some pros and cons:
- Pro: Your actual source for the helm chart in your git repo is very readable.
- Pro: The policy in your git repo will be valid to kyverno ( if it does not contain helm templating ) - so you can `kubectl apply` easily for testing.
- Pro: Sharing and working on policies together with non-helm users becomes trivial.
- Con: You need to run another step in CI before building your helm chart.
- Con: The actual helm chart is even less readable after CI.

Here is a full shell script which you can use in CI. It takes policies stored in a `policies` subfolder, executes the pre-build shown here and then copies them to a `helm/x/templates` subfolder:
```sh
#!/bin/bash
set -euo pipefail

placeholder="üüü"
# shellcheck disable=SC2016
open_brackets_escaped='{{ `{{` }}'
# shellcheck disable=SC2016
close_brackets_escaped='{{ `}}` }}'

disclaimer="# THIS FILE IS GENERATED - DO NOT EDIT MANUALLY"

replace () {
  local filename=$1
  local from=$2
  local to=$3
  sed -i.bak "s/$from/$to/g" "$filename" && rm "$filename".bak # https://stackoverflow.com/a/44877280
}

replace_all () {
  local filename=$1
  replace "$filename" '{{' $placeholder
  replace "$filename" '}}' "$close_brackets_escaped"
  replace "$filename" $placeholder "$open_brackets_escaped"
  replace "$filename" '\[\[' '{{'
  replace "$filename" '\]\]' '}}'

  echo $disclaimer | cat - $filename > $filename.modified

  mv $filename.modified $filename
}

mkdir -p $(pwd)/helm/CHANGEME/templates

cp -a $(pwd)/policies/. $(pwd)/helm/CHANGEME/templates

# based on https://github.com/koalaman/shellcheck/wiki/SC2044
while IFS= read -r -d '' filename
do
  replace_all "$filename"
done <   <(find "$(pwd)"/helm/CHANGEME/templates -name '*.yaml' -print0)
```

**Comment by MarcelMue** [comment]
TODO: Setup a small sample repo where maybe a github action is shown that takes a bunch of policies and does the pre-build magic.

**Comment by chipzoller** [comment]
This is great, @MarcelMue. Thanks very much.

**Comment by chipzoller** [comment]
Hey @MarcelMue just to let you know I'm adding this as a note into the docs now. Any more thoughts on your (excellent) idea of a GitHub Action which transforms a repo of Kyverno policies into a nicely-packaged Helm chart?
