### ISSUE TITLE
Update theme to display code block as full width

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/website#55]
The current / default theme does not use the full panel width for code blocks. Would be good to allow it to take more space and avoid a horizontal scroll. 

![image](https://user-images.githubusercontent.com/5489990/103332931-d18cb300-4a20-11eb-9489-15085d9e1560.png)

Also, not sure if the RHS side panel is always useful. Would be nice to remove for policy samples.

**Comment by chipzoller** [comment]
This is something I tackled in the theme I helped build. Full width would only work if all code blocks control line lengths, which isn't guaranteed. What would be better is an optional wrap lines button (or auto-function) which takes care of that.

As far as the side panel is concerned, maybe just my opinion but if this solution is only temporary, then I don't know I'd spend a whole lot of cycles trying to remove it.

**Comment by RinkiyaKeDad** [comment]
Can we even modify the original theme? I tried changing some of the CSS in the docsy files and received an error due to which the Hugo server didn't work. I'll try asking more about it on the [docsy repo](https://github.com/google/docsy).

**Comment by chipzoller** [comment]
Yes, we can. We have some working code for this and more related to the policy section.

**Comment by RinkiyaKeDad** [comment]
Hey @JimBugwadia - I found out where the CSS for this fix was. Changing `max-width` to `100%` (or 90% if some padding is still needed) in [this file](https://github.com/google/docsy/blob/master/assets/scss/support/_utilities.scss#L79) would fix this.
![full-width](https://user-images.githubusercontent.com/56963264/107635741-a937db80-6c91-11eb-951c-cbcd1003a730.png)
Two things though:
1. As shown in the above image, for some code blocks a horizontal scroll will still be needed.
2. Currently the `themes/docsy` folder is not present in our repository and is being pulled from [google/docsy](https://github.com/google/docsy) so we would need to have the docsy files actually present in our repository to edit the CSS, right?

**Comment by RinkiyaKeDad** [comment]
Hey @chipzoller! Do you plan to include this as part of the filters feature you showed in the UI? If not should I raise a PR?

**Comment by chipzoller** [comment]
Yes, this is planned.

**Comment by chipzoller** [comment]
@RinkiyaKeDad The new filter feature was just merged, however we didn't include this enhancement (honestly forgot).

**Comment by chipzoller** [comment]
Closing since this was implemented in kyverno.io/policies a while back (thank you, @onweru)
