### ISSUE TITLE
[Website internal] Sort Subjects on policies page alphabetically

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#566]
### Description

On the [policies page](https://kyverno.io/policies/), we'd like to sort the Subjects alphabetically as we are now getting to the point of scale (and growing) where this is making finding Subjects cumbersome. This was the result of some custom HTML and JavaScript which most likely needs very, very simple tweaks. It would be great to have this small enhancement to make the policy search process even better.

**Comment by chipzoller** [comment]
Not sorted:

![image](https://user-images.githubusercontent.com/29008123/176207386-fccdb32a-861b-438e-8874-dccd6ec2c558.png)

**Comment by chalin** [comment]
Oops, my bad (wasn't looking at the subjects -- glossed over the issue and thought it was for the page results)! Thanks.
