### ISSUE TITLE
[1.8.0] New container flags 

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#584]
### Description

Container flags `maxReportChangeRequests`, `splitPolicyReport` and `maxQueuedEvents` are added to 1.7.2 to for the memory issue. The issue is a placeholder to update docs if they enter GA in 1.8.0.

https://github.com/kyverno/kyverno/releases/tag/v1.7.2-rc1
https://github.com/kyverno/kyverno/pull/4233

**Comment by nathanielpitts-bestbuy** [comment]
Is there anywhere these new flags are currently documented aside from the release notes for 1.7.2? It would be very helpful to have some additional guidance on when and how to best use these new flags.

For example, `maxReportChangeRequests` suggests using a "small" threshold for large clusters, but does not offer guidance on how to determine that threshold value. Under which conditions does it make sense to use `splitPolicyReport` and `maxQueuedEvents`?

**Comment by chipzoller** [comment]
> Is there anywhere these new flags are currently documented aside from the release notes for 1.7.2?

Currently, no, that's what this issue is about.

@realshuting what is the likelihood that these flags will NOT be carried forward into 1.8.0?

**Comment by realshuting** [comment]
These flags will be supported in 1.8.0 until https://github.com/kyverno/kyverno/issues/4225 is in-place.

@npitts0811 - have you faced any issues with Kyverno performance or the reporting functionality? We are trying to collect more data and publish recommended setups for Kyverno. Would love to hear your use cases.

**Comment by npitts0811** [comment]
@realshuting No issues since we updated to 1.7.2 last month. Prior to that, we had similar memory as others had reported (I was closely following kyverno/kyverno#4072). At the time, I was exploring if those new flags would help us with our memory issues, but since moving to 1.7.2, our environment has been steady and stable without using the additional flags.

**Comment by chipzoller** [comment]
As of Kyverno 1.7.2, there is a new `splitPolicyReport` container flag (PR [here](https://github.com/kyverno/kyverno/pull/4147)) which, when set, will split a policy report per policy.

Closed by PR #4147

**Comment by chipzoller** [comment]
Closed in PR #625
