### ISSUE TITLE
[Bug] Status of compatibility with Kubernetes v1.24

### ISSUE THREAD

**Issue by dchirikov** [kyverno/website#590]
### Page link

https://kyverno.io/docs/installation/#compatibility-matrix

### Description

Hi devs,

thank you for the great project and amount or work you put in it.
I am not sure it is a bug or request from my side, but could you clarify the status of 1.24 Kubernetes?
Compatibility matrix shows it is not supported, but I found that this version is being tested e2e here:
https://github.com/kyverno/kyverno/blob/v1.7.2/.github/workflows/e2e.yaml#L25
So it makes me wonder that documentation for this is probably lagging behind.

Thank you in advance.

### Expected behavior

Update compatibility matrix

**Comment by dchirikov** [comment]
Thank you for the answer @chipzoller . Is there any ETA for 1.8.0 yet?

**Comment by chipzoller** [comment]
No ETA as of yet.

**Comment by chipzoller** [comment]
Not an actionable docs issue for now. Will update support matrix with each release.
