### ISSUE TITLE
[Enhancement] Add GitHub releases as an option for installing kyverno-cli

### ISSUE THREAD

**Issue by kranurag7** [kyverno/website#596]
### Description

Almost every time, I use GitHub [releases](https://github.com/kyverno/kyverno/releases) page in order to install the kyverno CLI in my system. If we add this, then the users following the docs don't have to clone the repo and neither they need `go/make` to build the CLI. 

- We can add it here https://kyverno.io/docs/kyverno-cli/#building-and-installing-the-cli 

### Proposed docs

```
curl -LO https://github.com/kyverno/kyverno/releases/download/v1.7.2/kyverno-cli_v1.7.2_linux_x86_64.tar.gz
sudo tar -xvf kyverno-cli_v1.7.2_linux_x86_64.tar.gz -C /usr/local/bin
```
- With this we can also copy the kyverno CLI to kubectl-kyverno without the need to krew. 
```
sudo cp /usr/local/bin/kyverno /usr/local/bin/kubectl-kyverno
```
- This is mostly useful when we are creating new VM, GitHub codespaces, Gitpod & CI environments. 

**NOTE:**
I have only checked this on Linux instances, and I'm not sure about windows. On windows, we are not releasing the binary on the release page in `.exe` format so I'm not sure whether it will be the same for windows.

**Comment by kranurag7** [comment]
@chipzoller Requesting you to please take a look at this, subject to your time availability. Please let me know if you think this is relevant.

**Comment by chipzoller** [comment]
Yes, this is more generic Linux knowledge, but it doesn't hurt to add it to the website. I will incorporate this in the next round of updates.
