### ISSUE TITLE
[Enhancement] Extend Pod Security Admission 

### ISSUE THREAD

**Issue by ToLToL** [kyverno/website#604]
### Description

Add documentation for the new rule `validate.PodSecurity` that [extends Pod Security admission for finer-grained and flexible policy control](https://github.com/kyverno/KDP/blob/main/proposals/extend_pod_security_admission.md).

Related PR: https://github.com/kyverno/kyverno/pull/4364

**Comment by chipzoller** [comment]
Control names are here: https://github.com/ToLToL/kyverno/blob/c0348e18cd0cb3c05bf739eb2bb5db213607d676/pkg/pss/mapping.go#L19-L85. They match up with the official PSS control names (parenthetical statements excluded).
