### ISSUE TITLE
[Enhancement] Add docs for clone multiple namespace resources

### ISSUE THREAD

**Issue by prateekpandey14** [kyverno/website#611]
### Description

Add documentation for Generate Policy with newly added clone multiple namespaces resources feature with examples

Related PR: 
- https://github.com/kyverno/kyverno/pull/4384 
- https://github.com/kyverno/kyverno/pull/4713

KDP:
- https://github.com/kyverno/KDP/pull/31

### Slack discussion

N/A

**Comment by K0more** [comment]
hey, can I get assigned to this.

**Comment by K0more** [comment]
Sorry for the delay I got busy with college, I am working on this.
