### ISSUE TITLE
[1.9] verifyImages can use K8s Secrets

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#613]
### Description

The `publicKey` field in a verifyImages rule can point to a Kubernetes Secret as documented [here](https://github.com/sigstore/cosign/blob/main/KMS.md#kubernetes-secret).

### Slack discussion

https://kubernetes.slack.com/archives/CLGR9BJU9/p1662587723629769?thread_ts=1662587603.370969&cid=CLGR9BJU9

**Comment by shahpratikr** [comment]
NOTE: while changing the documentation for this issue, we also need to consider changes from https://github.com/kyverno/kyverno/pull/5228
