### ISSUE TITLE
[Bug] Update Makefile command for building CLI

### ISSUE THREAD

**Issue by haroldo89** [kyverno/website#622]
### Page link

https://kyverno.io/docs/kyverno-cli/#building-the-cli-from-source

### Description

the latest version of MakeFile does not have the "cli" command, it causes confusion when trying to install the kyverno-cli from source

### Expected behavior

update the kyverno readme indicating that the correct command is "build-cli"

**Comment by gurpreet-legend** [comment]
Can I work on this issue?
