### ISSUE TITLE
[Enhancement] update autogen for pod controllers to mention json6902 patch 

### ISSUE THREAD

**Issue by zswanson** [kyverno/website#629]
### Description

The documentation for mutation policies with json6902 patches includes a small warning that these are not supported for autogen rules for Pods. However the autogen documentation page does **not** mention this, which led to some confusion as it seemed like it should be a supported use-case. 

https://kyverno.io/docs/writing-policies/mutate/#rfc-6902-jsonpatch <--- notes the json6902 exclusion
https://kyverno.io/docs/writing-policies/autogen/ <--- does not note the json6902 exclusion

Recommend adding some similar warning text to `docs/writing-policies/autogen/` that autogen is not enabled for patchesJson6902 mutation rules.

Additionally the text at https://kyverno.io/docs/writing-policies/mutate/#rfc-6902-jsonpatch has a somewhat confusing statement `mutations using patchesJson6902 to Pods directly is not supported` - since you **can** mutate pods directly with the json6902 patch, you just cannot get the autogen rules that also mutate pod **templates** in Controller resources.

### Slack discussion

https://kubernetes.slack.com/archives/CLGR9BJU9/p1664282697092249

**Comment by hitarth01** [comment]
Hey! I would like to work on this enhancement.
