### ISSUE TITLE
Clarification on generate existing behavior

### ISSUE THREAD

**Issue by amit-disc** [kyverno/website#634]
### Page link

https://kyverno.io/docs/writing-policies/generate/#generate-for-existing-resources

### Description

More of a question rather than bug, but could not find a question section.

`With Kyverno 1.7.0+, Kyverno supports the generate for existing resources. Generate existing policies are applied in the background which creates target resources based on the match statement within the policy. They may also optionally be configured to apply upon updates to the policy itself.
`

From what i understand by this text is that by default, kyverno will generate resources in existing namespace(namespaces which exist before policy was installed) based on background scan interval which is 1 hour by default and `generateExistingOnPolicyUpdate ` flag is only optional. Is my understanding correct? 

### Expected behavior

Validation of understanding above and more clear documentation.

**Comment by chipzoller** [comment]
No, that field is required if you want the generate existing behavior. And the generations will happen in the background but not in accordance with the background scan process, which is separate. "Asynchronously" may be a better word.

**Comment by amit-disc** [comment]
@chipzoller Thanks :) now its more clear. So in order to trigger the update, we need to update or create the policy. One more doubt if you have time to answer. How do we monitor those "async" generate? There seems to be no "gr" resources but only "ur" resources.

**Comment by chipzoller** [comment]
UR is the replacement for GR, so those are the ones you can check.

**Comment by chipzoller** [comment]
Closing as resolved. Feel free to respond or see us in the #kyverno channel on Kubernetes Slack for follow up.

**Comment by chipzoller** [comment]
It shouldn't matter so long as you write a policy that takes them into consideration, but that depends on your goals.
