### ISSUE TITLE
[Enhancement] Add signatureAlgorithm field in `verifyImages.attestors.entries.keys`

### ISSUE THREAD

**Issue by shahpratikr** [kyverno/website#639]
### Description

We need a way to specify signatureAlgorithm in policy which enables verifying public key with algorithm other than sha256. Raised PR in kyverno/kyverno to support this. We need to document this.

**Comment by chipzoller** [comment]
Since this field can be returned in a `kubectl explain` command, I think also including it in the documentation is probably a bit too much information especially since the current docs make no mention of signing algorithms to begin with.
