### ISSUE TITLE
Version documentation

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/website#64]
We need to manage doc variations across a few versions:

https://www.docsy.dev/docs/adding-content/versioning/

**Comment by JimBugwadia** [comment]
Here is a proposal to manage release versions:

1. Decide how many major and minor versions we support and add this somewhere in the docs.
2. Enable the version dropdown in Docsy
3. Update Netlify to create domains based on branch names.
4. `main` is always the latest released version.
5. Create a new branch for each new version e.g. v1.3.2, when we start adding docs for the version. 
6. When we release a new Kyverno version, branch main to v(x-1) i.e. the previous version, and merge v(x) i.e. the new version to main, and update version selection dropdowns.
7. Remove references to older branches based on #1. When all references to a version are deleted, delete the branch.

**Comment by JimBugwadia** [comment]
@chipzoller - lets discuss and finalize how to manage doc versions. Open to suggestions, if there are other ways that have worked well for folks

**Comment by chipzoller** [comment]
This sounds like a good approach. I'm just not familiar with this process in Docsy (or any other theme) so will take some playing around, I suspect.
