### ISSUE TITLE
[Bug] flag: backgroundScan is described as a timer while the flag is a boolean

### ISSUE THREAD

**Issue by WimDiepgrond** [kyverno/website#642]
### Page link

https://main.kyverno.io/docs/installation/#container-flags

### Description

On the Installation page under "container-flags" for "backgroundScan" a time is suggested while the flag is a boolean.
(7. backgroundScan: the interval (like 30s, 15m, 12h) for background processing. Default is set to 1h.) 

### Expected behavior

  -backgroundScan
    	Enable or disable background scan. (default true)

(this is stated in the container's logs)

**Comment by chipzoller** [comment]
It'll be fixed in a pending PR.
