### ISSUE TITLE
[Bug] imagePullSecret value does not exist in Global Anchor result example

### ISSUE THREAD

**Issue by Santosh1176** [kyverno/website#662]
### Page link

https://kyverno.io/docs/writing-policies/mutate/#global-anchor

### Description

In the explanation to Global Anchor example about adding the `imagePullSecret`. The example policy should result in adding the `imagePullSecret` to the Pod definition. But, the field is missing in the example result code snippet.

### Expected behavior

Add `imagePullSecret: my-secret` to the resulting Pod definition code snippet.

**Comment by chipzoller** [comment]
Thanks for the report! Fixing in PR #661
