### ISSUE TITLE
[Enhancement] Document new oci command in the Kyverno CLI

### ISSUE THREAD

**Issue by developer-guy** [kyverno/website#663]
### Description

We are working on implementing pull and push operations for policies from/to OCI registries. We should document this to explain how it works in general by clearly describing the CLI usage and the intent of why we implemented this.

_https://github.com/kyverno/kyverno/pull/5026_

/cc @eddycharly @chipzoller

**Comment by chipzoller** [comment]
Must set the env var `KYVERNO_EXPERIMENTAL` to `true` or `1` to view this command.
