### ISSUE TITLE
[Enhancement] Update Configmap flags settings

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#669]
### Description

Once https://github.com/kyverno/kyverno/issues/5148 is merged, we want to update the configmap flags settings on https://kyverno.io/docs/installation/#configmap-flags.

**Comment by XDRAGON2002** [comment]
@realshuting what all changes would updating the website require?

**Comment by chipzoller** [comment]
Linked issue (and PR) were closed. I see no action for this as the ConfigMap keys have not changed. The discussion was around their triggering in Helm versus the raw manifest.
