### ISSUE TITLE
[Enhancement] Document the deprecation of `validationFailureAction`: `audit` and `enforce`

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#672]
### Description

From Kyverno v1.9.0, upper case `validationFailureAction` will be supported `Audit`, `Enforce`.

Old failure actions `audit` and `enforce` are deprecated and will be removed in `v1.11.0` (2 minor releases after 1.9.0).

**Comment by chipzoller** [comment]
Warning implemented in https://github.com/kyverno/kyverno/pull/5219
