### ISSUE TITLE
[1.9] Document tracing/profiling better

### ISSUE THREAD

**Issue by palmobar** [kyverno/website#683]
### Description

Hello,
I'm trying to follow the https://kyverno.io/docs/monitoring/opentelemetry/ document, however the mentioned flags are not working as I'd expect them to (please see https://kubernetes.slack.com/archives/CLGR9BJU9/p1667819671013099 for details). In a nutshell when I set flags like:

```
        - --otelCollector=opentelemetrycollector
        - --otelConfig=grpc
        - --disableMetrics=false
        - --enableTracing=true
        - --metricsPort=8000
```

The container is showing an error: `2022/11/07 11:23:08 max retry time elapsed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address opentelemetrycollector: missing port in address"`

When I try to add the port then I see another error:

```
        - --otelCollector=opentelemetrycollector:8000
        - --otelConfig=grpc
        - --disableMetrics=false
        - --enableTracing=true
        - --metricsPort=8000
```

`2022/11/07 11:29:45 max retry time elapsed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address opentelemetrycollector:8000:8000: too many colons in address"`

I've tried many combinations but all of them failed in one way or another. I wish the documentation would've been clearer or the helm chart would support tracing/profiling.

### Slack discussion

https://kubernetes.slack.com/archives/CLGR9BJU9/p1667819671013099

**Comment by chipzoller** [comment]
Now that there is proper support in 1.9 for distributed tracing, this issue should really focus on that.

@eddycharly I need your help here.
