### ISSUE TITLE
[Enhancement] 1.8.2 publish performance metrics data

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#703]
### Description

Publish performance metrics for Kyverno v1.8.2. 

The data are collected using the tool ClusterLoader2, see https://github.com/kyverno/kyverno/wiki/Performance-Benchmarking to run the test.

Metrics data:

https://docs.google.com/document/d/1zO_dryL1JH6oJ0-pIenzWw7edCzxj4ZD4go0PzzyMC8/edit#heading=h.vgquy8pasjoa

**Comment by chipzoller** [comment]
@realshuting can we get the numbers for 1.9 testing?

**Comment by realshuting** [comment]
> @realshuting can we get the numbers for 1.9 testing?

Sure, I will update the doc for 1.9.

**Comment by chipzoller** [comment]
See also comments in the linked doc. Need more details on some of those points.
