### ISSUE TITLE
[1.9.0] Tags to enable ConfigMap cache via informers

### ISSUE THREAD

**Issue by shahpratikr** [kyverno/website#705]
### Description

To enable ConfigMap caching via informers, user need to provide labels `"cache.kyverno.io/enabled": "true"` in ConfigMap resources. We need to mention this in documents.

### Slack discussion

https://kubernetes.slack.com/archives/C032MM2CH7X/p1669169470285179

**Comment by chipzoller** [comment]
Please link to your PR which adds this capability, @shahpratikr
