### ISSUE TITLE
[1.9] Add documentation for new API PolicyException

### ISSUE THREAD

**Issue by Eileen-Yu** [kyverno/website#708]
### Description

The new feature `PolicyException` is introduced in this [PR](https://github.com/kyverno/kyverno/pull/5054).

The blog needs to cover:
- Basics on exception management
- How to restrict edits to policy exceptions
- Best practices

**Comment by Eileen-Yu** [comment]
@JimBugwadia I'd like to start with blogging `PolicyExceptions` based on this issue.

**Comment by chipzoller** [comment]
@Eileen-Yu I have made an initial write-up of the PolicyException feature. I would greatly appreciate any feedback you might have on it. The PR is liked above, and the docs preview can be found here: https://deploy-preview-733--kyverno.netlify.app/docs/writing-policies/exceptions/

**Comment by Eileen-Yu** [comment]
Thx @chipzoller ! It looks clear and concrete 👍
