### ISSUE TITLE
[Enhancement] Securing Container Base Images Using Kyverno Policies @cloudnativefm podcast to be added in the resources section. 

### ISSUE THREAD

**Issue by Saim-Safdar** [kyverno/website#714]
### Description

we need to access the base image information of the container images first. Thanks to ko, Buildpacks, and Docker Buildx, we can quickly provide build information while building container images. According to that, we should be determining which base images can be used and which of them cannot before allowing them to run on production systems. This is where Kyverno comes into play. Please add this episode of [@cloudnativefm] Securing Base images with kyverno on a resources section under documentation. (https://www.youtube.com/channel/UC7B9fl8jQ8TEdOCypF4g3Wg)

**Comment by chipzoller** [comment]
Thanks for this! It would be very simple to add this in a pull request yourself if you'd like to contribute 🙂

**Comment by Saim-Safdar** [comment]
Do I need to submit a pull on the main branch, I need info on which branch I use for a pull request.

**Comment by chipzoller** [comment]
Yes, `main` branch only. We will handle the cherry pick.

**Comment by Saim-Safdar** [comment]
Easier, if we can have a simple form to fill out and the rest is up to the team to figure out the best way to add YouTube or blog links to add it in the kyverno website.
