### ISSUE TITLE
[Render] Support for CleanupPolicies

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#740]
### Description

The render utility needs to be updated to account for CleanupPolicies so they can be rendered to Markdown and displayed on the site.

**Comment by VedRatan** [comment]
I can take up this one. @chipzoller

**Comment by chipzoller** [comment]
Note that in order to fully support the actual displaying of cleanup policies on kyverno.io will also require some work on the website side as well.

**Comment by VedRatan** [comment]
> Note that in order to fully support the actual displaying of cleanup policies on kyverno.io will also require some work on the website side as well.

Could you please point me to the task, what needs to be done for displaying the policies on kyverno.io? @chipzoller

**Comment by chipzoller** [comment]
The filtering system needs to be updated to add a category for Cleanup and possibly other parsing/selection logic. I don't know all the locations which need to be updated and how.

**Comment by VedRatan** [comment]
Oh ok, I'll try to figure it out.

**Comment by CIPHERTron** [comment]
Hey @VedRatan are you still working on this or can I take it up?

**Comment by VedRatan** [comment]
Hi @CIPHERTron, I hope you're having a great day, yes I am working on this one.
