### ISSUE TITLE
[1.9] Add documentation for `time_now`, `time_parse`, `time_to_cron` and `time_add` JMESPath filters

### ISSUE THREAD

**Issue by Vishal-Chdhry** [kyverno/website#741]
### Description

Three new custom JMES filters have been added
1. `time_now`: prints the current time in RFC 3339 format. https://github.com/kyverno/kyverno/pull/5813
2. `time_to_cron`: takes in an absolute time (RFC 3339) and outputs a cron expression (string) which can be used when generating a (Cluster)CleanupPolicy https://github.com/kyverno/kyverno/pull/5814
3. `time_add`: RFC3339 + scalar (duration) with the sum being RFC3339. https://github.com/kyverno/kyverno/pull/5817
4. `time_parse`

**Comment by chipzoller** [comment]
Kindly link to the PRs in your first comment so we can follow them back for documentation material.
