### ISSUE TITLE
[Bug] The created-by example policy is broken

### ISSUE THREAD

**Issue by Setomidor** [kyverno/website#748]
### Page link

https://kyverno.io/docs/writing-policies/variables/#variables-from-admission-review-requests

### Description

If you apply the example created-by policy to your cluster, any pod controller will be unable to create new pods because the created-by label gets populated with an illegal value.

`Warning  FailedCreate      7m3s   job-controller  Error creating: Pod "gpu-example-mglnh" is invalid: metadata.labels: Invalid value: "system:serviceaccount:kube-system:job-controller": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')`

### Expected behavior

Everything working when using the policy

### Slack discussion

https://kubernetes.slack.com/archives/CLGR9BJU9/p1674134897983679

**Comment by chipzoller** [comment]
Convert example to use annotation instead of label.
