### ISSUE TITLE
[Bug]  Background Scan container flag is misleading and expensive scans

### ISSUE THREAD

**Issue by joaomo** [kyverno/website#753]
### Page link

https://kyverno.io/docs/installation/#container-flags

### Description

While reading through the documentation on the container flags it seems like the `backgroundScan` [container flag](https://github.com/kyverno/kyverno/blob/v1.8.5/cmd/kyverno/main.go#L129) would disable background scans but it just stops background scan reports from being emitted, setting the `backgroundScanWorkers` to 0 also does not disable the background scans from running. And to understand that the issue for our peaks in resource usage was the background scans we had to check the background scan metrics emitted.

In order to disable the background scans all policies need to have the /spec/background field set to false.

Contrary to what is in the documentation [here](https://kyverno.io/docs/policy-reports/) when talking about resource filters, the background scans are very resource intensive causing significant peaks in both memory and cpu.

### Expected behavior

At least 3 changes should be made to the documentation:

- Have the `backgroundscan` flag documentation explain that it only disables the reports and that the scans will be executed regardless. 
- Document better what is the purpose for the backgroundScanWorkers variable
- Give some estimates for different number of policy runs and number of resources to estimate resource usage for background scans(For us it was a spike of 100x for cpu usage and 5x for memory usage).

**Comment by chipzoller** [comment]
Will be closed by PR #843. Scaling guidelines is being tracked in https://github.com/kyverno/kyverno/issues/6944.
