### ISSUE TITLE
[Bug] Description of `background` Policy Setting is Misleading

### ISSUE THREAD

**Issue by LaikaN57** [kyverno/website#757]
### Page link

https://kyverno.io/docs/writing-policies/policy-settings/#:~:text=background%3A%20controls%20if%20rules%20are%20applied%20to%20existing%20resources%20during%20a%20background%20scan.%20Defaults%20to%20%E2%80%9Ctrue%E2%80%9D

### Description

> `background`: controls if rules are applied to existing resources during a background scan. Defaults to “true”.

I think there are 2 levels of issues/solutions here either:
1) Semantically the word "rules" is too generic and should read "validation rules" and the word "applied" is just incorrect according to the below documentation. Doing some word replacement here might be the quick win.
2) The entire `background` description should be rewritten/updated to better match what seems to be the current source of truth (ie. the doc below).

https://kyverno.io/docs/writing-policies/background/

### Expected behavior

This is answered in the description.

### Slack discussion

https://kubernetes.slack.com/archives/CLGR9BJU9/p1612459243238900

**Comment by chipzoller** [comment]
1. Background also applies to verifyImages rules and not just validation rules. The word "applies" seems accurate to me. The below documentation link you shared states this in the opening paragraph:

>The application of policies to existing resources is referred to as background scanning and is enabled by default unless background is set to false in a policy like shown below in the snippet.

2. We can update the definition of the `background` field on [this page](https://kyverno.io/docs/writing-policies/policy-settings/) if that makes it clearer.

**Comment by LaikaN57** [comment]
> We can update the definition of the background field on [this page](https://kyverno.io/docs/writing-policies/policy-settings/) if that makes it clearer.

@chipzoller yes, that is my proposal. I am just not the best word smith. Just the code monkey trying to use the docs :) Thanks!

**Comment by yrs147** [comment]
Hi @chipzoller  , I would like to work on this issue can you please assign this to me
