### ISSUE TITLE
Update docs on Helm chart

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/website#76]
The Kyverno helm chart now bundles policies for pod security standards:

https://github.com/kyverno/kyverno/pull/1493

We should mention this in the docs and provide pointers for more details.

For the YAML install, would be good to reference the command line option to install the same policies.

**Comment by chipzoller** [comment]
What are the flags to install these policies during installation time of Kyverno?

**Comment by chipzoller** [comment]
@JimBugwadia ☝️

**Comment by chipzoller** [comment]
This docs update needs to await the stable release of 1.3.2 since chart 1.3.1 does not incorporate these PSPs.

**Comment by hikhvar** [comment]
I disabled the default set of policies by setting the value of `podSecurityStandard` to `disabled`. Can you please put that into the documentation as well?

**Comment by chipzoller** [comment]
Yes, thanks @hikhvar this is being addressed.
