### ISSUE TITLE
[Enhancement] Document missing 1.9 metrics

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#760]
### Description

Metrics in https://github.com/kyverno/kyverno/pull/5494 are not documented.

**Comment by Biswajit-Behera** [comment]
Hi @chipzoller,
Can I work on this issue??

**Comment by chipzoller** [comment]
Sure, assigned.

**Comment by Biswajit-Behera** [comment]
Thank You.
I will work on this.
If I have any updates or query will ask!

**Comment by Biswajit-Behera** [comment]
I am working on Prometheus Metrics in the given document. Am I on the right way??

**Comment by Biswajit-Behera** [comment]
I am working on Prometheus Metrics in the given document. Am I on the right way??
I'd need some more context to understand.

**Comment by chipzoller** [comment]
```
kyverno_controller_reconcile
kyverno_controller_requeue
kyverno_controller_drop
```
