### ISSUE TITLE
[Enhancement] Add documentation for PolicyExceptions spec.background field implementation

### ISSUE THREAD

**Issue by yimikao** [kyverno/website#763]
### Description

Related Issue: https://github.com/kyverno/kyverno/pull/6127#issuecomment-1419427140

**Comment by Vishal-Chdhry** [comment]
`omit-events`: Set this flag to a comma sperated list of PolicyViolation, PolicyApplied, PolicyError, PolicySkipped to disable events, e.g. --omit-events=PolicyApplied,PolicyViolation
