### ISSUE TITLE
[Enhancement] Add documentation for `omit-events` flag

### ISSUE THREAD

**Issue by Vishal-Chdhry** [kyverno/website#764]
### Description

References
- PR: https://github.com/kyverno/kyverno/pull/7010
- Discussion: https://github.com/kyverno/kyverno/pull/6072 (closed this PR because of merge issues, has a conversation regarding the implementation)

**Comment by realshuting** [comment]
The flag is added to all controllers except the cleanup controller https://github.com/kyverno/kyverno/pull/7010#issuecomment-1532820357.

**Comment by Vishal-Chdhry** [comment]
`omit-events`: Set this flag to a comma sperated list of `PolicyViolation`, `PolicyApplied`, `PolicyError`, `PolicySkipped` to disable events, e.g. `--omit-events=PolicyApplied,PolicyViolation`
