### ISSUE TITLE
[Enhancement] Fix docs on CLI `jp` command

### ISSUE THREAD

**Issue by VedRatan** [kyverno/website#768]
### Description

The current Kyverno version has new CLI structure with regard to the jp command, so the documentation should be updated in accordance to the current functionality of the jp command.

current documentation is at: [https://kyverno.io/docs/kyverno-cli/#jp](url)

run the below command to test the latest command structure of jp

`kyverno jp -h`

### Slack discussion

https://kubernetes.slack.com/archives/C032MM2CH7X/p1676477549697309?thread_ts=1676477212.442289&cid=C032MM2CH7X

**Comment by VedRatan** [comment]
I would like to work on this issue. If there is no one to take this up.

**Comment by chipzoller** [comment]
Thanks for offering, but if you don't mind I'll take this one for the sake of language consistency.

**Comment by Vyom-Yadav** [comment]
Update https://kyverno.io/docs/kyverno-cli/#building-the-cli-from-source too, `CLI_BIN` has [changed](https://github.com/kyverno/kyverno/commit/fc79ca96a282127db818a394b8971cb1502922fd).
```
CLI_BIN        := $(CLI_DIR)/kubectl-kyverno
```

**Comment by VedRatan** [comment]
Sure, no problem @chipzoller.
