### ISSUE TITLE
ClusterPolicy creation failed on Minikube Kubernetes [Bug] 

### ISSUE THREAD

**Issue by rayuduanand** [kyverno/website#772]
### Page link

https://kyverno.io/docs/introduction/

### Description

Thank you for the beautiful documentation for learn.

When i am testing the kyverno policy in minikube, cluster policy creation is failed with error.
The ClusterPolicy "require-labels" is invalid: spec.validationFailureAction: Unsupported value: "Enforce": supported values: "audit", "enforce"

##########
kubectl create -f- << EOF
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-labels
spec:
  validationFailureAction: Enforce ---------> enforce
  rules:
  - name: check-for-labels
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "label 'app.kubernetes.io/name' is required"
      pattern:
        metadata:
          labels:
            app.kubernetes.io/name: "?*"
EOF
################

### Expected behavior

Cluster policy code snippet needs to corrected. 

Note:- I have tested it on Minikube.
minikube v1.26.1 on Darwin 12.6
Preparing Kubernetes v1.24.3 on Docker 20.10.17 ...

kubectl create -f- << EOF
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-labels
spec:
  validationFailureAction: Enforce -------> enforce
  rules:
  - name: check-for-labels
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "label 'app.kubernetes.io/name' is required"
      pattern:
        metadata:
          labels:
            app.kubernetes.io/name: "?*"
EOF

Policy created after validationFailureAction changed to enforce from "Enforce"

**Comment by chipzoller** [comment]
You are not installing Kyverno 1.9 in this case.

**Comment by rayuduanand** [comment]
Yes, I have installed v1.8.5

**Comment by chipzoller** [comment]
Instructions on kyverno.io always apply to the most current version. If you're on 1.8, use the drop-down to find that version of the docs.
