### ISSUE TITLE
[Bug] autogeninternals still referenced in container-flags

### ISSUE THREAD

**Issue by zswanson** [kyverno/website#774]
### Page link

https://kyverno.io/docs/installation/#container-flags

### Description

the autogeninternals CLI flag was removed in 1.9.0 but it is still mentioned as a valid config at https://kyverno.io/docs/installation/#container-flags

### Expected behavior

This flag should be removed from the docs

**Comment by chipzoller** [comment]
Thanks, will fix. Also updated release notes with mention of it (was actually in RC.1 release notes).
