### ISSUE TITLE
[Enhancement] Dark mode for website

### ISSUE THREAD

**Issue by JayadityaGit** [kyverno/website#786]
### Description

I am a student who recently started learning frontend web development, and I would like to contribute by adding dark theme feature. However, I want to exclude the homepage from this change. Can you please let me know what technologies I need to implement this feature successfully?

Thank you in advance for your help.

**Comment by chipzoller** [comment]
Hello and welcome. Kyverno uses the [docsy theme](https://github.com/google/docsy) for Hugo. I would recommend contributing there as they already have the following issues open to add this support:

https://github.com/google/docsy/issues/331
https://github.com/google/docsy/issues/391
