### ISSUE TITLE
[Enhancement] New configmap flag

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#787]
### Description

This PR  https://github.com/kyverno/kyverno/pull/6499 adds a new configmap flag `excludeBackgroundUsernames` and exclude the Kyverno background controller user by default.

This needs to be added to the doc here https://kyverno.io/docs/installation/#configmap-flags.

EDIT Chip: I think this was walked back and converted to a container flag in PR [6790](https://github.com/kyverno/kyverno/pull/6790).

**Comment by chipzoller** [comment]
Also add `webhookAnnotations` from PR [6579](https://github.com/kyverno/kyverno/pull/6579).

**Comment by chipzoller** [comment]
Also add `excludeRoles` and `excludeClusterRoles` from PR [6779](https://github.com/kyverno/kyverno/pull/6779).

**Comment by chipzoller** [comment]
Also `excludeGroups` in PR [6789](https://github.com/kyverno/kyverno/pull/6789).

**Comment by chipzoller** [comment]
Add flags for default registry configs.
