### ISSUE TITLE
The hyperlinks open in the same page as of the website

### ISSUE THREAD

**Issue by Kanika637** [kyverno/website#791]
### Page link

https://kyverno.io/

### Description

- In this section, the hyperlinks "mailing list" ,  "Kyverno channel on Kubernetes Slack" , "community page" open in the same page.

![Screenshot_20230317_204329](https://user-images.githubusercontent.com/84350895/225945727-5a2a6ea9-9ca3-4ac0-8d8f-d791ee1e7ff2.png)

- I will make them redirect to their independent pages, which is the appropriate way.

### Expected behavior

They should redirect to their independent pages.

**Comment by win20** [comment]
Hello, just wanted to ask, did you say you were working on this issue? Because it seems to still be on the website and I could get this sorted if that's okay with you? Thanks.

**Comment by Kanika637** [comment]
No, actually I opened this issue as I want to work on this, but I am waiting that someone could assign it to me and I can make a PR.
