### ISSUE TITLE
[doc] Verify Notary signature with Kyverno

### ISSUE THREAD

**Issue by FeynmanZhou** [kyverno/website#804]
### Description

Kyverno supports Notary signature verification at https://github.com/kyverno/kyverno/pull/6011. I see there is a draft doc https://docs.google.com/document/d/1VQYBcQQbtGldbSlhNRnFHnqY6GCekOe22hwoR9oTdc4/edit# owned by @JimBugwadia . Do we have the plan to add this doc to the Kyverno website? If this guide is available at Kyverno documentation, we could link this doc in the Notary documentation.

**Comment by JimBugwadia** [comment]
Hi @FeynmanZhou - Notary support is scheduled for v1.10, and we will be updating the docs soon.

**Comment by chipzoller** [comment]
Would you be able to assist with taking docs for this one, @JimBugwadia?

**Comment by JimBugwadia** [comment]
Yes, will do.

**Comment by chipzoller** [comment]
@JimBugwadia we still need this for the docs
