### ISSUE TITLE
[Enhancement] Clarify usage of `install.yaml` in production

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/website#808]
### Description

The docs currently state:

https://kyverno.io/docs/installation/#install-kyverno-using-helm

> Kyverno can be deployed via a Helm chart–the only supported method for a production install–which is accessible either through the Kyverno repo or on [ArtifactHub](https://artifacthub.io/packages/helm/kyverno/kyverno).

However, the `install.yaml` file is part of the official release artifacts and is generated using `helm template`.

We need to clarify how users can leverage the `install.yaml` for production installations.

**Comment by chipzoller** [comment]
Closed in #833
