### ISSUE TITLE
[Enhancement] Update hyperlinks on the Resources Page to open in new tab

### ISSUE THREAD

**Issue by Jai-Solania-29** [kyverno/website#811]
### Page link

https://kyverno.io/resources/

### Description

Hyperlinks on the Resources Page that are redirecting the user to a different website (other than Kyverno) are not getting redirected to a separate tab.

![Screenshot 2023-03-18 at 12 04 05 AM](https://user-images.githubusercontent.com/90816300/229866251-b3dd90cf-f11a-4202-829c-4e4c22da9a3d.png)

![Screenshot 2023-04-04 at 10 41 50 PM](https://user-images.githubusercontent.com/90816300/229867453-5436728c-9d75-4645-b655-ffe72405105b.png)

I want to work on this issue, I will make them redirect to their independent pages, which is the appropriate way.

### Expected behavior

They should redirect to their independent pages.

**Comment by chipzoller** [comment]
@Jai-Solania-29 are you actively working on this?

**Comment by Jai-Solania-29** [comment]
Hey @chipzoller , I'll make my PR by tonight.

**Comment by Jai-Solania-29** [comment]
Hey @chipzoller, I have made my PR.
