### ISSUE TITLE
[Bug] 1.10 docs missing config for new default image registry option

### ISSUE THREAD

**Issue by zswanson** [kyverno/website#816]
### Page link

https://main.kyverno.io/docs/installation/#configmap-flags

### Description

Documentation is missing for new 1.10 feature https://github.com/kyverno/kyverno/pull/4715 that adds config of default image registry.

### Expected behavior

The new config map flags should appear at https://main.kyverno.io/docs/installation/#configmap-flags

From the PR: 
```
| config.defaultRegistry | string | `"docker.io"` | The registry hostname used for the image mutation. |
| config.enableDefaultRegistryMutation | bool | `true` | Enable registry mutation for container images. Enabled by default. |
```

**Comment by chipzoller** [comment]
Covered here for consolidation: https://github.com/kyverno/website/issues/787#issuecomment-1501174029
