### ISSUE TITLE
Support Git paths in CLI for policies

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#84]
See https://github.com/kyverno/kyverno/issues/1422.

**Comment by chipzoller** [comment]
Adding to 1.3.2 milestone.

**Comment by chipzoller** [comment]
@NoSkillGirl is this something you want to add yourself (since you already have an outstanding PR for that section of the docs)?

**Comment by chipzoller** [comment]
@NoSkillGirl would you like to handle this one?

**Comment by NoSkillGirl** [comment]
Regarding Git path, @vyankyGH is working on the related issues. It will be better if he can update the doc.
