### ISSUE TITLE
[Bug] Incorrect documentation description for client-queries

### ISSUE THREAD

**Issue by mvaalexp** [kyverno/website#862]
### Page link

https://kyverno.io/docs/monitoring/client-queries/

### Description

Metric Value

Counter - An only-increasing integer representing the total number of policy-level changes associated with a metric sample.

Appears to be a copy/paste from 

https://kyverno.io/docs/monitoring/policy-changes/

Title description could also be more clear:
queries per second (QPS) from Kyverno

### Expected behavior

Counter with appropriate description. 

This metric can be used to track the number of queries per second (QPS) from Kyverno to the Kubernetes API server.

**Comment by chipzoller** [comment]
Fixed on main, will be pulled into release branch soon: https://main.kyverno.io/docs/monitoring/client-queries/
