### ISSUE TITLE
[Bug] Copy pasting command from documentation did not work

### ISSUE THREAD

**Issue by crimbler2** [kyverno/website#863]
### Page link

https://kyverno.io/docs/writing-policies/external-data-sources/

### Description

On this page the command
```kubectl get --raw /api/v1/namespaces | kyverno jp "items[*].{name: metadata.name, creationTime: metadata.creationTimestamp}"```
is documented.
Copy pasting that did not work.

### Expected behavior

I've expected to see the list provided in the documentation.

By changing the command a little bit to `... | kyverno jp query ...`, it worked.

**Comment by chipzoller** [comment]
Thanks. Already fixed in main, awaiting pulling into prod:

https://main.kyverno.io/docs/writing-policies/external-data-sources/
