### ISSUE TITLE
[Bug] Secret names in case of Self Signed Certs

### ISSUE THREAD

**Issue by harindersingh** [kyverno/website#872]
### Page link

https://release-1-7-0.kyverno.io/docs/installation/#certificate-management

### Description

To create the required Secrets, use the following commands (do not change the Secret names)

The Secret names should be changed in case the namespace is not "Kyverno". I faced this issue as installation for Kyverno was a non-Kyverno namespace(using Helm) and even after creating the secrets with `kyverno-svc.kyverno.svc.*` name the Kyverno helm chart created another set of secrets and ignored the I had already created.

Resolution: Secrets should be of the format `kyverno-svc.<namespace where Kyverno will be installed>.svc.*`

### Expected behavior

Secrets created should have accepted by Helm command to install Kyverno using the self-signed certs placed manually.

**Comment by Rohan-Dah** [comment]
Hii. I'd like to work on the issue

**Comment by chipzoller** [comment]
Closed in #916
