### ISSUE TITLE
[Enhancement] skipResourceFilters description is misleading

### ISSUE THREAD

**Issue by jemag** [kyverno/website#886]
### Description

Currently the description for `skipResourceFilters` https://github.com/kyverno/website/blob/37f6c83f2dbeeebb67d1f6f9a0d4889cd7625267/content/en/docs/Installation/customization.md#L303-L303
describes the false value, which is a bit misleading.

Usually it would be easier to understand if it used either the true value like:
` ignore the ConfigMap's resourceFilters when performing background report scans`

or a more general approach like:
 `whether to skip the ConfigMap's resourceFilters or not when performing background report scans. Setting the value to false will take the resourceFilters into account`

### Slack discussion

https://kubernetes.slack.com/archives/CLGR9BJU9/p1685571600886239?thread_ts=1685561945.070269&cid=CLGR9BJU9

**Comment by chipzoller** [comment]
Please review https://github.com/kyverno/website/pull/899

**Comment by jemag** [comment]
LGTM @chipzoller 

As a side note, (this is not related to the documentation), but it might be easier in the future to avoid terminology like `skipXXXX` which has the mental burden of having to negate the value to know if it is present.

Basically, instead of: 
`skipResourceFilters `
`skip_headers `
`skip_log_headers `
It might be simpler to just have flags like 
`resourceFiltersEnabled`
`headers_enabled`
`log_headers_enabled`
and set their default value accordingly. 
I feel it is easier to reason about, although I guess this is subjective.

**Comment by chipzoller** [comment]
Agree, that would have been better.
