### ISSUE TITLE
[Enhancement] `round()` docs

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#909]
### Description

Document new `round()` filter in https://github.com/kyverno/kyverno/pull/7489

**Comment by Rexbeast2** [comment]
@chipzoller I would like to work on this issue.

**Comment by Rexbeast2** [comment]
@chipzoller can you provide a sample policy to include in the documentation?

**Comment by chipzoller** [comment]
Write a policy which uses a simple `variable` context entry in which the value is a floating-point number, for example `1.45345`. Use the `round()` filter to take this context variable and round it to one decimal place, perhaps as the value of a new annotation. The resulting value of the annotation should then be `1.5`.
