### ISSUE TITLE
[Bug] Navigation link not working

### ISSUE THREAD

**Issue by anusha94** [kyverno/website#914]
### Page link

https://kyverno.io/docs/writing-policies/cleanup/

### Description

In the section that describes about giving additional permissions to the cleanup controller for removing resources, the link to `Customizing Permissions` is broken. It navigates to a `localhost` endpoint.

<img width="1398" alt="image" src="https://github.com/kyverno/website/assets/10369205/3441e170-55c1-4a53-b8e3-772726befa4d">

### Expected behavior

I would expect this to be linked to the section in the website that describes Customizing Permissions.

**Comment by chipzoller** [comment]
Will be fixed by #913
