### ISSUE TITLE
Add documentation for test CLI command

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#92]
See https://github.com/kyverno/kyverno/issues/1564.

**Comment by chipzoller** [comment]
@vyankyGH Is this something you can add? We're a bit behind and trying to close out the 1.3.2 milestone.

**Comment by vyankyGH** [comment]
> @vyankyGH Is this something you can add? We're a bit behind and trying to close out the 1.3.2 milestone.

I will complete this ASAP!
