### ISSUE TITLE
[Enhancement] `render` utility does not clean directories

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#929]
### Description

When using the `-c` flag to `render`, it does not remove directories. Unsure if bug or oversight.

**Comment by prady0t** [comment]
can you provide a bit more context?

**Comment by chipzoller** [comment]
> can you provide a bit more context?

Sorry for the ridiculously long delay here. To provide more context, when the `-c` flag is used it only cleans files from the existing directories under the destination. It does not _remove_ those directories. This is a problem because the names of those directories corresponds to upstream directories. When this removal doesn't happen and an upstream directory is renamed it results in a duplication effect which we don't want. The only way to avoid that is to clean all files and directories and render all anew.

**Comment by A-5ingh** [comment]
@chipzoller Could you please provide the steps to reproduce this issue. I am new to go lang. I am able to setup the code and run the website using github codespaces.

**Comment by chipzoller** [comment]
Clone the website repo, build `render`, then run it with the `-c` flag pointed to the directory with the policies. It does not remove the directories inside the policies folder.

**Comment by A-5ingh** [comment]
I see @chipzoller, I think I found the issue. It has to do something with 
https://github.com/kyverno/website/blob/f82fc7b4199349bef3dd633be264ea0c947b208a/render/render.go#L223-L226
This piece of code is not returning the files in sub-directories to clean. I will check and submit a PR soon.
