### ISSUE TITLE
[Bug] v1.10 Release Notes references normalize_image() but should be image_normalize()

### ISSUE THREAD

**Issue by divbell** [kyverno/website#937]
### Page link

https://github.com/kyverno/kyverno/releases/tag/v1.10.0

### Description

The critical information about breaking changes has an incorrect JMESPath function:

`Mutation rules which change the image field in a Pod spec and which relied on docker.io being silently added by Kyverno (when it was not explicitly defined in the image) will need to be adjusted to either use the images.*.registry [predefined variable](https://kyverno.io/docs/writing-policies/variables/#variables-from-container-images) `

`or the new normalize_image() JMESPath filter.`

 Further down the wall of text, it names the correct function:

`Added a new JMESPath filter image_normalize() which can be used to show the fully normalized image string which includes things like default registry (configurable in the Kyverno ConfigMap) and latest tag when no tag is defined. (https://github.com/kyverno/kyverno/pull/6911)`

This was highly confusing to me as I could not find this normalize_image() function in the documentation at https://main.kyverno.io/docs/writing-policies/jmespath/.  

### Expected behavior

Release notes should say image_normalize(), not normalize_image().

**Comment by chipzoller** [comment]
Thanks, fixed.
