### ISSUE TITLE
Document set operations for In and NotIn

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#94]
See https://github.com/kyverno/kyverno/issues/1367.

**Comment by RinkiyaKeDad** [comment]
I'll get to it. Do each of the operators listed under the [Operators](https://kyverno.io/docs/writing-policies/preconditions/#operators) section require a subsection or should I just document that In and NotIn operators now support set operations?

**Comment by chipzoller** [comment]
No they don't require their own subsection. Just try and capture it as best you can and we can play with as necessary.
