### ISSUE TITLE
[Enhancement] Add Policy Annotations description to documentation

### ISSUE THREAD

**Issue by dirsigler** [kyverno/website#965]
### Description

During my research for Kyverno I found the [Policies available online](https://kyverno.io/policies/?policytypes=generate+mutate+Pod%2520Security%2520Admission+validate+verifyImages). 
These make use of the specific annotations reserved for Kyverno but unfortunately there is no documentation alongside them nor on the pages describing policies itself: https://kyverno.io/docs/writing-policies/

@chipzoller kindly provided me with the [overview of annotations which are hosted here on GitHub](https://github.com/kyverno/policies/wiki/Kyverno-annotations).
In my opinion it would make sense to also add the overview of annotations and their description to a new page called "Policy Annotations" underneath [Writing Policies](https://kyverno.io/docs/writing-policies/).
I am also open for other ideas on where to place them in the documentation.

### Slack discussion

https://cloud-native.slack.com/archives/C02CEARLA3D/p1694681954431589

**Comment by dirsigler** [comment]
It seems I was confusing something on the original reason for the annotations. If I understand correctly they are **ONLY** to add additional information for the community based policies available here on GitHub and the [Kyverno Policies page](https://kyverno.io/policies/?policytypes=generate+mutate+Pod%2520Security%2520Admission+validate+verifyImages). So there is no real need to specify them on own internal hosted policies.

**Comment by dirsigler** [comment]
Okay, then I think we can close this issue, because I somehow first thought they are also used in my Kyverno installation to limit the installation targets. Thank you very much for your input!

**Comment by chipzoller** [comment]
I just remembered that because this was asked in the past, I put a note [here](https://kyverno.io/policies/).
