### ISSUE TITLE
[Bug] Typo on JMESPath page (missing 'it')

### ISSUE THREAD

**Issue by umka1332** [kyverno/website#972]
### Page link

https://kyverno.io/docs/writing-policies/jmespath/#:~:text=Whatever%20the%20value%20of%20the%20namespace%20key%20is%20will%20be%20inserted%20where%20the%20expression%20is%20written.

### Description

The page has a sentence:
"Whatever the value of the namespace key is will be inserted where the expression is written."
Where a word 'it' is missing

### Expected behavior

The sentence should be:
"Whatever the value of the namespace key is, it will be inserted where the expression is written."

**Comment by satyazzz123** [comment]
Can I work on this issue?
